// GENERATED by gen-pages.mjs — do not edit.
import P0 from "@/app/app/page.js";
import P1 from "@/app/app/copilot/page.js";
import P2 from "@/app/app/leads/page.js";
import P3 from "@/app/app/quotes/page.js";
import P4 from "@/app/app/estimate-reviews/page.js";
import P5 from "@/app/app/jobs/page.js";
import P6 from "@/app/app/invoices/page.js";
import P7 from "@/app/app/plans/page.js";
import P8 from "@/app/app/appointments/page.js";
import P9 from "@/app/app/tasks/page.js";
import P10 from "@/app/app/clients/page.js";
import P11 from "@/app/app/equipment/page.js";
import P12 from "@/app/app/chat/page.js";
import P13 from "@/app/app/settings/team/page.js";
import P14 from "@/app/app/subcontractors/page.js";
import P15 from "@/app/app/scheduler/page.js";
import P16 from "@/app/app/schedule/page.js";
import P17 from "@/app/app/clock/page.js";
import P18 from "@/app/app/settings/team/timesheets/page.js";
import P19 from "@/app/app/time-off/page.js";
import P20 from "@/app/app/safety/page.js";
import P21 from "@/app/app/payroll/page.js";
import P22 from "@/app/app/settings/expense-tracking/page.js";
import P23 from "@/app/app/purchasing/page.js";
import P24 from "@/app/app/fleet/page.js";
import P25 from "@/app/app/analytics/benchmark/page.js";
import P26 from "@/app/app/analytics/kpis/page.js";
import P27 from "@/app/app/marketing/page.js";
import P28 from "@/app/app/marketing/designer/page.js";
import P29 from "@/app/app/funnels/page.js";
import P30 from "@/app/app/receptionist/page.js";
import P31 from "@/app/app/crew-inbox/page.js";
import P32 from "@/app/app/messages/page.js";
import P33 from "@/app/app/settings/refer/page.js";
import P34 from "@/app/app/help/page.js";
import P35 from "@/app/app/settings/account-billing/page.js";
import P36 from "@/app/app/settings/company/page.js";
import P37 from "@/app/app/settings/migration/page.js";
import P38 from "@/app/app/settings/product-updates/page.js";
import P39 from "@/app/app/settings/branding/page.js";
import P40 from "@/app/app/settings/language/page.js";
import P41 from "@/app/app/activity/page.js";
import P42 from "@/app/app/settings/availability/page.js";
import P43 from "@/app/app/settings/leave/page.js";
import P44 from "@/app/app/settings/booking-page/page.js";
import P45 from "@/app/app/settings/work-areas/page.js";
import P46 from "@/app/app/settings/products/page.js";
import P47 from "@/app/app/settings/services/page.js";
import P48 from "@/app/app/settings/material-costs/page.js";
import P49 from "@/app/app/settings/cabinet-rates/page.js";
import P50 from "@/app/app/settings/overhead/page.js";
import P51 from "@/app/app/settings/custom-fields/page.js";
import P52 from "@/app/app/settings/quote-email/page.js";
import P53 from "@/app/app/settings/email-templates/page.js";
import P54 from "@/app/app/settings/templates/page.js";
import P55 from "@/app/app/settings/translations/page.js";
import P56 from "@/app/app/settings/checklists/page.js";
import P57 from "@/app/app/settings/job-photo-tags/page.js";
import P58 from "@/app/app/settings/messages/page.js";
import P59 from "@/app/app/settings/follow-ups/page.js";
import P60 from "@/app/app/settings/notifications/page.js";
import P61 from "@/app/app/settings/email-domain/page.js";
import P62 from "@/app/app/settings/payments/page.js";
import P63 from "@/app/app/settings/meta-ads/page.js";
import P64 from "@/app/app/settings/ai-credit/page.js";
import P65 from "@/app/app/settings/payroll/page.js";
import P66 from "@/app/app/settings/website/page.js";
import P67 from "@/app/app/settings/instant-quotes/page.js";
import P68 from "@/app/app/settings/lead-form/page.js";
import P69 from "@/app/app/settings/links/page.js";
import P70 from "@/app/app/settings/voice/page.js";
import P71 from "@/app/app/settings/ai-employee/page.js";
import P72 from "@/app/app/settings/reviews/page.js";
export const PAGES = {
  "app/app/page.js": P0,
  "app/app/copilot/page.js": P1,
  "app/app/leads/page.js": P2,
  "app/app/quotes/page.js": P3,
  "app/app/estimate-reviews/page.js": P4,
  "app/app/jobs/page.js": P5,
  "app/app/invoices/page.js": P6,
  "app/app/plans/page.js": P7,
  "app/app/appointments/page.js": P8,
  "app/app/tasks/page.js": P9,
  "app/app/clients/page.js": P10,
  "app/app/equipment/page.js": P11,
  "app/app/chat/page.js": P12,
  "app/app/settings/team/page.js": P13,
  "app/app/subcontractors/page.js": P14,
  "app/app/scheduler/page.js": P15,
  "app/app/schedule/page.js": P16,
  "app/app/clock/page.js": P17,
  "app/app/settings/team/timesheets/page.js": P18,
  "app/app/time-off/page.js": P19,
  "app/app/safety/page.js": P20,
  "app/app/payroll/page.js": P21,
  "app/app/settings/expense-tracking/page.js": P22,
  "app/app/purchasing/page.js": P23,
  "app/app/fleet/page.js": P24,
  "app/app/analytics/benchmark/page.js": P25,
  "app/app/analytics/kpis/page.js": P26,
  "app/app/marketing/page.js": P27,
  "app/app/marketing/designer/page.js": P28,
  "app/app/funnels/page.js": P29,
  "app/app/receptionist/page.js": P30,
  "app/app/crew-inbox/page.js": P31,
  "app/app/messages/page.js": P32,
  "app/app/settings/refer/page.js": P33,
  "app/app/help/page.js": P34,
  "app/app/settings/account-billing/page.js": P35,
  "app/app/settings/company/page.js": P36,
  "app/app/settings/migration/page.js": P37,
  "app/app/settings/product-updates/page.js": P38,
  "app/app/settings/branding/page.js": P39,
  "app/app/settings/language/page.js": P40,
  "app/app/activity/page.js": P41,
  "app/app/settings/availability/page.js": P42,
  "app/app/settings/leave/page.js": P43,
  "app/app/settings/booking-page/page.js": P44,
  "app/app/settings/work-areas/page.js": P45,
  "app/app/settings/products/page.js": P46,
  "app/app/settings/services/page.js": P47,
  "app/app/settings/material-costs/page.js": P48,
  "app/app/settings/cabinet-rates/page.js": P49,
  "app/app/settings/overhead/page.js": P50,
  "app/app/settings/custom-fields/page.js": P51,
  "app/app/settings/quote-email/page.js": P52,
  "app/app/settings/email-templates/page.js": P53,
  "app/app/settings/templates/page.js": P54,
  "app/app/settings/translations/page.js": P55,
  "app/app/settings/checklists/page.js": P56,
  "app/app/settings/job-photo-tags/page.js": P57,
  "app/app/settings/messages/page.js": P58,
  "app/app/settings/follow-ups/page.js": P59,
  "app/app/settings/notifications/page.js": P60,
  "app/app/settings/email-domain/page.js": P61,
  "app/app/settings/payments/page.js": P62,
  "app/app/settings/meta-ads/page.js": P63,
  "app/app/settings/ai-credit/page.js": P64,
  "app/app/settings/payroll/page.js": P65,
  "app/app/settings/website/page.js": P66,
  "app/app/settings/instant-quotes/page.js": P67,
  "app/app/settings/lead-form/page.js": P68,
  "app/app/settings/links/page.js": P69,
  "app/app/settings/voice/page.js": P70,
  "app/app/settings/ai-employee/page.js": P71,
  "app/app/settings/reviews/page.js": P72,
};
