// content/help/index.js
//
// GENERATED by scripts/build-help-content.mjs from lib/help/tree.js — do not
// edit by hand. One lazy loader per language per category, so a page imports
// only the module it renders and Next can bundle each one statically.

export const LOADERS = {
  en: {
    "getting-started": () => import("./en/getting-started.js"),
    "leads-and-quotes": () => import("./en/leads-and-quotes.js"),
    "jobs-and-scheduling": () => import("./en/jobs-and-scheduling.js"),
    "invoices-and-payments": () => import("./en/invoices-and-payments.js"),
    "clients": () => import("./en/clients.js"),
    "team-and-access": () => import("./en/team-and-access.js"),
    "marketing-and-website": () => import("./en/marketing-and-website.js"),
    "messages": () => import("./en/messages.js"),
    "mobile-and-crew": () => import("./en/mobile-and-crew.js"),
    "reports-and-insights": () => import("./en/reports-and-insights.js"),
    "settings": () => import("./en/settings.js"),
    "billing-and-subscription": () => import("./en/billing-and-subscription.js"),
    "what-your-clients-see": () => import("./en/what-your-clients-see.js"),
    "integrations": () => import("./en/integrations.js"),
  },
  fr: {
    "getting-started": () => import("./fr/getting-started.js"),
    "leads-and-quotes": () => import("./fr/leads-and-quotes.js"),
    "jobs-and-scheduling": () => import("./fr/jobs-and-scheduling.js"),
    "invoices-and-payments": () => import("./fr/invoices-and-payments.js"),
    "clients": () => import("./fr/clients.js"),
    "team-and-access": () => import("./fr/team-and-access.js"),
    "marketing-and-website": () => import("./fr/marketing-and-website.js"),
    "messages": () => import("./fr/messages.js"),
    "mobile-and-crew": () => import("./fr/mobile-and-crew.js"),
    "reports-and-insights": () => import("./fr/reports-and-insights.js"),
    "settings": () => import("./fr/settings.js"),
    "billing-and-subscription": () => import("./fr/billing-and-subscription.js"),
    "what-your-clients-see": () => import("./fr/what-your-clients-see.js"),
    "integrations": () => import("./fr/integrations.js"),
  },
  es: {
    "getting-started": () => import("./es/getting-started.js"),
    "leads-and-quotes": () => import("./es/leads-and-quotes.js"),
    "jobs-and-scheduling": () => import("./es/jobs-and-scheduling.js"),
    "invoices-and-payments": () => import("./es/invoices-and-payments.js"),
    "clients": () => import("./es/clients.js"),
    "team-and-access": () => import("./es/team-and-access.js"),
    "marketing-and-website": () => import("./es/marketing-and-website.js"),
    "messages": () => import("./es/messages.js"),
    "mobile-and-crew": () => import("./es/mobile-and-crew.js"),
    "reports-and-insights": () => import("./es/reports-and-insights.js"),
    "settings": () => import("./es/settings.js"),
    "billing-and-subscription": () => import("./es/billing-and-subscription.js"),
    "what-your-clients-see": () => import("./es/what-your-clients-see.js"),
    "integrations": () => import("./es/integrations.js"),
  },
};
