// app/(marketing)/compare/summary.js
//
// What one card on /compare can honestly promise, derived from the data.
//
// ══ Why this is its own module ═════════════════════════════════════════════
//
// It used to live in ./page.js beside the markup. The markup became a client
// component when these pages stopped being English-only, and a pure function
// that four other things import has no business crossing that boundary with
// it: ./page.js re-exports this so scripts/check-compare-pages.mjs keeps
// importing it from where it always did, and ./CompareIndex.js imports it
// directly. One definition either way.
//
// ══ Why the summary on each card is computed, not written ══════════════════
//
// The obvious version is four cards with a sentence typed under each: "Jobber
// — three prices compared". It would be wrong within a quarter. Whether a
// competitor's figure publishes is decided by withholdReason against a date,
// and that answer moves on its own: an unresolved question settled in
// competitors.js adds rows, and ninety days without a re-check removes them. A
// hand-written count is AGENTS.md failure class 4 — the copy nobody looks at
// when the data changes — attached to a claim about somebody else's prices.

import {
  PRICE_AMOUNT,
  PRICE_ON_REQUEST,
  SOURCED_PUBLISHER,
  withholdReason,
} from "@/lib/marketing/competitors";

/**
 * Returns finished sentences rather than counts, so a caller cannot assemble a
 * different claim out of the same numbers. Every branch is reachable with the
 * data as it stands: Housecall Pro has amounts whose currency their own footer
 * states, ServiceTitan has only request-a-price tiers, Projul has three amounts
 * whose currency their page never names, QuoteIQ has ten, and Jobber has both
 * amounts and a large withheld pile.
 *
 * ══ Why the currency line is separate ══════════════════════════════════════
 *
 * The first sentence used to end "in the currency they print it in", and it was
 * true of every competitor on this index when it was written. It stopped being
 * true the day Projul's three amounts began publishing: their page prints no
 * currency at all and the one beside those figures is the owner's signed
 * assertion. A card that keeps the old ending says Projul printed something
 * they did not — a false statement about a competitor, generated by a sentence
 * nobody edited. So the clause is conditional on the figures' own
 * `currencySourcing`, and where it does not hold the card says what actually
 * happened instead of going quiet.
 *
 * ══ On `t` ════════════════════════════════════════════════════════════════
 *
 * Optional, English fallback at every call site. Called with two arguments —
 * which is how the check script calls it — this returns exactly the English it
 * returned before /compare was translated.
 *
 * One English sentence CHANGED in the move, and deliberately: the singular
 * branch used to read "1 of their published price", the plural noun stripped by
 * an `n === 1 ? "price" : "prices"` that was wrong English to begin with ("one
 * of their prices" takes the plural). Every other language would have had to
 * reproduce that mistake to stay parallel with it.
 */
export function comparisonSummary(competitor, asOf, t) {
  const say = (key, fallback, values) =>
    typeof t === "function"
      ? t(key, fallback, values)
      : String(fallback).replace(/\{(\w+)\}/g, (m, name) =>
          values?.[name] !== undefined ? String(values[name]) : m,
        );

  const published = competitor.figures.filter((f) => withholdReason(f, asOf) === null);
  const amounts = published.filter((f) => f.price?.kind === PRICE_AMOUNT);
  const onRequest = published.filter((f) => f.price?.kind === PRICE_ON_REQUEST);
  const withheldCount = competitor.figures.length - published.length;
  // Absence is not read as "off their page" here either: withholdReason already
  // refuses a figure that records no provenance for its currency, so anything
  // that is not SOURCED_PUBLISHER got there by somebody signing for it.
  const asserted = amounts.filter((f) => f.price?.currencySourcing !== SOURCED_PUBLISHER);

  const lines = [];
  if (amounts.length > 0) {
    lines.push(
      asserted.length === 0
        ? say(
            "compare.summary.amountsSourced",
            "{count} of their published prices can be set beside ours, in the currency they print it in.",
            { count: amounts.length },
          )
        : say(
            "compare.summary.amounts",
            "{count} of their published prices can be set beside ours.",
            { count: amounts.length },
          ),
    );
  }
  if (asserted.length > 0) {
    lines.push(
      say(
        "compare.summary.asserted",
        "{count} of those name no currency on their own page, so the comparison says whose judgement the currency is rather than printing it as theirs.",
        { count: asserted.length },
      ),
    );
  }
  if (onRequest.length > 0) {
    lines.push(
      say(
        "compare.summary.onRequest",
        "{count} of their tiers publish no amount at all and ask you to request one.",
        { count: onRequest.length },
      ),
    );
  }
  if (amounts.length === 0 && onRequest.length === 0) {
    lines.push(
      say(
        "compare.summary.none",
        "Nothing they publish can be compared with a FieldQuo price.",
      ),
    );
  }
  if (withheldCount > 0) {
    lines.push(
      withheldCount === 1
        ? say(
            "compare.summary.withheldOne",
            "{count} further figure is held back, shown with the reason.",
            { count: withheldCount },
          )
        : say(
            "compare.summary.withheld",
            "{count} further figures are held back, each shown with the reason.",
            { count: withheldCount },
          ),
    );
  }
  return lines;
}
