// lib/sales/discovery/mergedReads.js
//
// What a survivor is allowed to say that was observed about a row merged
// into it.
//
// ══ Why the evidence stays where it was ═══════════════════════════════════
//
// mergeProspects.js retires the other rows and leaves their ProspectEvidence,
// ProspectCapability, ProspectTechnology and ProspectInference rows ATTACHED
// to them. Two reasons, and the second is the one that decides it:
//
//   * provenance — an observation is about the page that was crawled, and
//     the retired row is the record of which page that was;
//   * the uniques — capabilities are unique per (prospect, code) and
//     inferences per (prospect, kind). Moving them onto a survivor that has
//     its own ONLINE_BOOKING row means dropping one of the two, and the whole
//     point of retiring rather than deleting is that nothing is dropped.
//
// So the union happens on READ. This is the one function that does it, used
// by both places a human looks at one prospect's analysis: the superadmin's
// detail (/api/platform/sales/prospects/[id]) and the rep's card
// (/api/sales/queue). Pure `unionAnalysis` does the merging so
// scripts/check-sales-merge.mjs can assert the rule; `loadMergedAnalysis` is
// the two-query wrapper.
//
// ══ The rule ══════════════════════════════════════════════════════════════
//
//   evidence      all of it, every retired row's, appended after the
//                 survivor's own. Nothing about evidence is per-prospect
//                 unique; more observations are more, never a conflict.
//   capabilities  the survivor's own row for a code WINS; a retired row's
//   technologies  fills only a code the survivor has no row for. Same for a
//   inferences    technology code and an inference kind. A rep reading "no
//                 online booking" sees the verdict on the site the survivor
//                 was crawled on; the retired row's verdict about a second
//                 site fills gaps, it does not overrule.
//   opportunities NOT unioned. Derived from the capability set, cited to
//                 evidence, regenerated by the pipeline; a recommendation
//                 computed for a different row is not this row's.
//
// Every borrowed row carries `fromProspectId` so a screen can say where it
// was seen, and `evidenceIds` on borrowed rows still resolve — the evidence
// they cite came along in the same union.
import { mergedFromIds } from "./mergeProspects";

/**
 * Pure. `own` is the survivor's four lists; `borrowed` the retired rows',
 * each row carrying its `prospectId`.
 */
export function unionAnalysis(own = {}, borrowed = {}) {
  const tag = (rows) => (rows || []).map((r) => ({ ...r, fromProspectId: r.prospectId }));
  const fillBy = (mine, theirs, keyOf) => {
    const have = new Set((mine || []).map(keyOf));
    const out = [...(mine || [])];
    for (const row of tag(theirs)) {
      const k = keyOf(row);
      if (have.has(k)) continue;
      have.add(k);
      out.push(row);
    }
    return out;
  };
  return {
    evidence: [...(own.evidence || []), ...tag(borrowed.evidence)],
    capabilities: fillBy(own.capabilities, borrowed.capabilities, (r) => r.code),
    technologies: fillBy(own.technologies, borrowed.technologies, (r) => r.technologyCode),
    inferences: fillBy(own.inferences, borrowed.inferences, (r) => r.kind),
    borrowedFrom: [...new Set([...(borrowed.evidence || []), ...(borrowed.capabilities || []), ...(borrowed.technologies || []), ...(borrowed.inferences || [])].map((r) => r.prospectId))],
  };
}

/**
 * The survivor's analysis lists, unioned with its merged-from rows'.
 *
 * `prospect` is a row read WITH its own capabilities / technologies /
 * inferences / evidence included, and with `mergedFrom`. Returns the four
 * lists plus `borrowedFrom`; for a row nothing was merged into, returns the
 * lists unchanged and no second query.
 */
export async function loadMergedAnalysis(db, prospect, { evidenceTake = 400 } = {}) {
  const own = {
    evidence: prospect?.evidence || [],
    capabilities: prospect?.capabilities || [],
    technologies: prospect?.technologies || [],
    inferences: prospect?.inferences || [],
  };
  const ids = mergedFromIds(prospect);
  if (!ids.length) return { ...own, borrowedFrom: [] };
  const [evidence, capabilities, technologies, inferences] = await Promise.all([
    db.prospectEvidence.findMany({ where: { prospectId: { in: ids } }, orderBy: { observedAt: "desc" }, take: evidenceTake }),
    db.prospectCapability.findMany({ where: { prospectId: { in: ids } } }),
    db.prospectTechnology.findMany({ where: { prospectId: { in: ids } } }),
    db.prospectInference.findMany({ where: { prospectId: { in: ids } } }),
  ]);
  return unionAnalysis(own, { evidence, capabilities, technologies, inferences });
}
