// lib/media/cloudinaryUrl.js
//
// resizedUrl() lived in lib/cloudinary.js until the photo annotator needed
// it from a "use client" component (app/components/photoAnnotator/
// PhotoAnnotatorEditor.js — it opens the editor against a resized variant so
// a 12–48MP phone photo doesn't hand a mobile browser a multi-thousand-pixel
// canvas to draw on; see lib/jobs/photoAnnotation.js#ANNOTATOR_MAX_WIDTH).
//
// lib/cloudinary.js's own top-level `cloudinary.config(...)` call means
// importing ANYTHING from that file pulls in the `cloudinary` npm package —
// a Node SDK that touches `fs`/`https`, which does not belong in a client
// bundle and would fail (or silently bloat) the real Next build the moment a
// "use client" file imported it. resizedUrl() itself never touched that SDK
// — it's pure string surgery on a URL — so it moves here, to a module with
// no server-only dependency, and lib/cloudinary.js re-exports it so every
// existing server-side caller (lib/jobs/photoReport.js, lib/ai/images.js)
// keeps working unchanged.
export function resizedUrl(url, { width = 1536 } = {}) {
  if (typeof url !== "string") return url;
  const marker = "/upload/";
  const i = url.indexOf(marker);
  if (i === -1) return url;

  const head = url.slice(0, i + marker.length);
  const tail = url.slice(i + marker.length);
  const w = Math.max(1, Math.round(Number(width) || 1536));
  // Valid immediately after `/upload/` whatever already follows it — a
  // version segment (`v169.../`) or an existing transformation both still
  // parse correctly with ours inserted in front.
  return `${head}w_${w},c_limit,q_auto,f_auto/${tail}`;
}

/**
 * The still frame a <video> shows before anybody presses play.
 *
 * ── Why a poster at all ────────────────────────────────────────────────────
 *
 * A <video> with no poster renders as a black rectangle until the browser has
 * pulled enough of the file to decode a frame — and on a phone in a driveway
 * that is several seconds of a bubble that looks broken. Worse, iOS Safari
 * will not decode a frame at all until the user interacts, so the black box is
 * permanent there. A poster makes the clip look like what it is: a picture of
 * the room, with a play button on it.
 *
 * ── Why Cloudinary makes it and we do not ──────────────────────────────────
 *
 * Because the alternative is a second stored asset, generated by a second job,
 * that can be missing while the video is present. Cloudinary derives a still
 * from a video URL by asking for it: `so_0` seeks to the first second, and
 * changing the extension to `.jpg` is what tells it to deliver an image rather
 * than a clip. One URL, no queue, nothing to get out of step.
 *
 * `so_0` rather than a percentage: a clip that opens on a dark frame is a
 * poster nobody can read, but "1% into an unknown duration" is not better and
 * is harder to reason about. The first second is what every messaging app
 * shows.
 *
 * Returns null — NOT the video URL — when this is not a Cloudinary upload URL
 * or not a video one. The caller renders a video with no poster in that case,
 * which is a plainer bubble; handing an <img> a video URL would be the broken
 * image this whole module exists to avoid.
 */
export function videoPosterUrl(url, { width = 800 } = {}) {
  if (typeof url !== "string") return null;
  const marker = "/video/upload/";
  const i = url.indexOf(marker);
  if (i === -1) return null;

  const head = url.slice(0, i + marker.length);
  const tail = url.slice(i + marker.length);
  const w = Math.max(1, Math.round(Number(width) || 800));
  // The extension carries the format, so an existing one is replaced rather
  // than appended — `clip.mp4.jpg` is a 404, and a URL with no extension at
  // all is Cloudinary's own valid form for "deliver the stored format".
  const withoutQuery = tail.split("?")[0];
  const lastSegment = withoutQuery.split("/").pop() || "";
  const base = lastSegment.includes(".")
    ? withoutQuery.slice(0, withoutQuery.length - (lastSegment.length - lastSegment.lastIndexOf(".")))
    : withoutQuery;
  return `${head}so_0,w_${w},c_limit,q_auto/${base}.jpg`;
}

/**
 * A variant cropped to EXACTLY `width`x`height` — `c_fill`, not `c_limit`.
 *
 * ── Why a second function instead of a `crop` option on resizedUrl ─────────
 *
 * The two answer different questions and only one of them is safe for the
 * caller that needs this. `c_limit` says "no bigger than", so the delivered
 * size depends on the source photo — fine for a vision read, useless for
 * lib/marketing/jobPost.js, which lays a photo into a fixed panel on a canvas
 * it composes SERVER-SIDE and therefore never gets to measure. A fabric
 * `image` object carries its own `width`/`height` in the saved document and
 * fabric treats them as a crop box on load: guess them and the browser
 * renders a corner of the photo at the wrong scale, silently, in a post that
 * goes out under the contractor's name. Asking Cloudinary for a known size is
 * what makes those two numbers knowable without ever fetching the file.
 *
 * `c_fill` with the default (centre) gravity rather than `g_auto`: auto
 * gravity is a better crop when it is enabled, and a delivery error when it
 * is not. A composition that has to be right on every deployment takes the
 * transformation that exists on all of them.
 *
 * A URL with no `/upload/` marker is returned unchanged, same as resizedUrl —
 * and callers that depend on the delivered size must therefore refuse a URL
 * that isn't one of this deployment's own uploads BEFORE calling this. See
 * isUploadedUrl() in lib/jobs/documents.js, which is the check
 * lib/marketing/jobPostSource.js applies for exactly this reason.
 */
export function filledUrl(url, { width, height } = {}) {
  if (typeof url !== "string") return url;
  const marker = "/upload/";
  const i = url.indexOf(marker);
  if (i === -1) return url;

  const w = Math.max(1, Math.round(Number(width) || 1));
  const h = Math.max(1, Math.round(Number(height) || 1));
  const head = url.slice(0, i + marker.length);
  const tail = url.slice(i + marker.length);
  return `${head}w_${w},h_${h},c_fill,q_auto,f_auto/${tail}`;
}
