// lib/sales/playbook/store.js
//
// Where a playbook, an objection and an experiment assignment live — and the
// one honest thing this file has to say today.
//
// ══ THE TABLES ARE NOT IN prisma/schema.prisma YET ═══════════════════════
//
// Five models are needed and none of them exist. The exact definitions are in
// lib/sales/playbook/schema.pending.prisma, ready to paste. They were not
// added here because the schema file is held by concurrent work and a third
// edit under two others is how the merges went wrong earlier — STATUS.md's own
// "Blocked, not forgotten" note records that happening.
//
// So this module answers `storeState()` from the generated Prisma client
// rather than from a constant, and everything downstream branches on the
// answer:
//
//   - READS work today. Playbooks and objections fall back to the seed
//     libraries, marked `source: "built-in"`, so selection, the script, the
//     talking-point gate and the whole preview screen are live and correct.
//   - WRITES refuse, loudly, with the model names in the message. The console
//     renders no edit control at all while the tables are absent — a `Coming
//     soon` panel is honest and a dead button is not.
//   - The banner saying so is COMPUTED from the client, never asserted. That
//     is the exact lesson from the TechnologySignature screen, whose
//     hard-coded "nothing reads these patterns yet" went stale the day a
//     detector shipped and left a check asserting the wrong behaviour.
//
// The day the models land, nothing in this file changes and every control
// appears.
import { db } from "@/lib/db";
import { seedObjections } from "./objections";
import { seedPlaybooks } from "./defaults";

/**
 * The Prisma delegates this module needs, and the model each one is.
 *
 * Keyed by delegate name because that is what can actually be probed on the
 * client — a model that is not in the schema has no delegate, and no amount of
 * reading the schema file at runtime would be as truthful.
 */
export const REQUIRED_MODELS = Object.freeze({
  salesPlaybook: "SalesPlaybook",
  salesObjection: "SalesObjection",
  salesPlaybookExperiment: "SalesPlaybookExperiment",
  salesPlaybookAssignment: "SalesPlaybookAssignment",
  prospectTalkingPoint: "ProspectTalkingPoint",
});

export const PENDING_SCHEMA_FILE = "lib/sales/playbook/schema.pending.prisma";

/** Thrown by every write path while the tables are absent. Never swallowed. */
export class PlaybookStoreUnavailable extends Error {
  constructor(missing) {
    super(
      `The playbook tables are not in the database yet. Missing: ${missing.join(", ")}. ` +
        `The definitions are ready in ${PENDING_SCHEMA_FILE}; add them to prisma/schema.prisma ` +
        "and run `npx prisma db push`.",
    );
    this.name = "PlaybookStoreUnavailable";
    this.missing = missing;
  }
}

/**
 * Computed, every time. Not cached: the client is regenerated by a build and a
 * cached "not ready" would outlive the thing it describes.
 */
export function storeState(client = db) {
  const missing = Object.entries(REQUIRED_MODELS)
    .filter(([delegate]) => !client?.[delegate])
    .map(([, model]) => model);
  return {
    ready: missing.length === 0,
    missing,
    pendingSchemaFile: PENDING_SCHEMA_FILE,
  };
}

function requireStore(client = db) {
  const state = storeState(client);
  if (!state.ready) throw new PlaybookStoreUnavailable(state.missing);
  return state;
}

// ── Reads ──────────────────────────────────────────────────────────────────

/**
 * Every playbook, database first, seed library second.
 *
 * `source` travels with the row so nothing downstream has to guess, and the
 * console can say "these are the built-in four, nothing has been saved" rather
 * than implying somebody wrote them.
 */
export async function loadPlaybooks({ includeInactive = false, client = db } = {}) {
  if (!storeState(client).ready) {
    const rows = seedPlaybooks().map((p) => ({ ...p, source: "built-in", id: p.key }));
    return includeInactive ? rows : rows.filter((p) => p.active);
  }

  const rows = await client.salesPlaybook.findMany({
    where: includeInactive ? {} : { active: true },
    orderBy: [{ priority: "desc" }, { key: "asc" }],
  });

  // An empty table is NOT the same as an absent one, and it does not fall back
  // to the seeds. Somebody deleting every playbook meant to delete every
  // playbook, and quietly resurrecting four is the destructive-operation-
  // labelled-as-cosmetic failure in reverse.
  return rows.map((r) => ({ ...r, stages: Array.isArray(r.stages) ? r.stages : [], source: "db" }));
}

export async function loadObjections({ includeInactive = false, client = db } = {}) {
  if (!storeState(client).ready) {
    const rows = seedObjections().map((o) => ({ ...o, source: "built-in", id: o.code }));
    return includeInactive ? rows : rows.filter((o) => o.active);
  }

  const rows = await client.salesObjection.findMany({
    where: includeInactive ? {} : { active: true },
    orderBy: [{ priority: "desc" }, { code: "asc" }],
  });
  return rows.map((r) => ({ ...r, source: "db" }));
}

export async function loadExperiments({ playbookKey = null, activeOnly = true, client = db } = {}) {
  // No table means no experiment, and that is the truthful answer rather than
  // an inconvenience: there is nowhere to store an assignment, so §38's "stored
  // before the call" cannot be satisfied, so no experiment may run.
  if (!storeState(client).ready) return [];

  return client.salesPlaybookExperiment.findMany({
    where: {
      ...(activeOnly ? { active: true, stoppedAt: null } : {}),
      ...(playbookKey ? { playbookKey } : {}),
    },
    orderBy: [{ createdAt: "asc" }],
  });
}

/** Everything one prospect's script needs, in one place. */
export async function loadProspectInputs(prospectId, { client = db } = {}) {
  const [prospect, capabilities, technologies, opportunities] = await Promise.all([
    client.prospect.findUnique({ where: { id: prospectId } }),
    client.prospectCapability.findMany({ where: { prospectId } }),
    client.prospectTechnology.findMany({ where: { prospectId } }),
    client.prospectOpportunity.findMany({
      where: { prospectId },
      orderBy: [{ rank: "asc" }],
    }),
  ]);
  return { prospect, capabilities, technologies, opportunities };
}

// ── Writes ─────────────────────────────────────────────────────────────────

/**
 * The assignment, read-or-create, in that order.
 *
 * The stored row ALWAYS wins. Re-deriving would move a prospect between arms
 * when somebody edits the weights, and every call already made would then be
 * filed under a script the rep never read — see experiments.js's header.
 *
 * `deriveVariant` is passed in rather than imported so the caller owns the
 * choice, and so this function has no opinion a rep could influence: there is
 * no parameter here that takes a variant.
 */
export async function readOrCreateAssignment(
  { experiment, prospectId, salesRepId = null, derive },
  { client = db } = {},
) {
  requireStore(client);

  const existing = await client.salesPlaybookAssignment.findUnique({
    where: { experimentId_prospectId: { experimentId: experiment.id, prospectId } },
  });
  if (existing) return { assignment: existing, created: false, refusal: null };

  const { variantKey, bucket, refusal } = derive(experiment, prospectId);
  if (!variantKey) return { assignment: null, created: false, refusal };

  // Two reps opening the same prospect at once must not produce two rows, and
  // must not produce an error either. The unique index decides; the loser
  // reads back what the winner wrote.
  try {
    const assignment = await client.salesPlaybookAssignment.create({
      data: {
        experimentId: experiment.id,
        prospectId,
        variantKey,
        bucket,
        salesRepId,
        assignedBy: "system",
      },
    });
    return { assignment, created: true, refusal: null };
  } catch {
    const raced = await client.salesPlaybookAssignment.findUnique({
      where: { experimentId_prospectId: { experimentId: experiment.id, prospectId } },
    });
    if (raced) return { assignment: raced, created: false, refusal: null };
    throw new Error("The variant assignment could not be written and could not be read back.");
  }
}

/**
 * Replace this prospect's stored talking points for one playbook.
 *
 * Delete-then-insert inside one transaction rather than an upsert per point:
 * a regeneration produces a different NUMBER of sentences, and leaving the
 * surplus behind would show a rep two arguments written under two different
 * models.
 */
export async function storeTalkingPoints(
  { prospectId, playbookKey, points, model = null },
  { client = db } = {},
) {
  requireStore(client);

  return client.$transaction(async (tx) => {
    await tx.prospectTalkingPoint.deleteMany({ where: { prospectId, playbookKey } });
    if (!points?.length) return [];
    await tx.prospectTalkingPoint.createMany({
      data: points.map((p) => ({
        prospectId,
        playbookKey,
        stageKey: p.stageKey,
        capabilityCode: p.capabilityCode,
        text: p.text,
        source: p.source,
        evidenceIds: p.evidenceIds,
        ruleCode: p.ruleCode,
        ruleVersion: p.ruleVersion,
        model,
      })),
    });
    return tx.prospectTalkingPoint.findMany({ where: { prospectId, playbookKey } });
  });
}

export async function loadStoredTalkingPoints({ prospectId, playbookKey }, { client = db } = {}) {
  if (!storeState(client).ready) return [];
  return client.prospectTalkingPoint.findMany({
    where: { prospectId, ...(playbookKey ? { playbookKey } : {}) },
    orderBy: [{ generatedAt: "desc" }],
  });
}

/**
 * Write the seed libraries into the database, once.
 *
 * This is the "install the starter playbooks" button, not a seed script — the
 * standing rule is explicit that a seed script is not a UI. It creates and
 * never updates: a superadmin who has edited COMPETITIVE_DISPLACEMENT must not
 * have their words replaced by a button labelled "install defaults".
 */
export async function installDefaults({ client = db, adminId = null } = {}) {
  requireStore(client);

  const playbooks = seedPlaybooks();
  const objections = seedObjections();

  const [existingPlaybooks, existingObjections] = await Promise.all([
    client.salesPlaybook.findMany({ select: { key: true } }),
    client.salesObjection.findMany({ select: { code: true } }),
  ]);
  const havePlaybook = new Set(existingPlaybooks.map((p) => p.key));
  const haveObjection = new Set(existingObjections.map((o) => o.code));

  const newPlaybooks = playbooks.filter((p) => !havePlaybook.has(p.key));
  const newObjections = objections.filter((o) => !haveObjection.has(o.code));

  const result = {
    playbooksCreated: newPlaybooks.map((p) => p.key),
    objectionsCreated: newObjections.map((o) => o.code),
    playbooksSkipped: playbooks.length - newPlaybooks.length,
    objectionsSkipped: objections.length - newObjections.length,
  };

  // The audit row is written INSIDE the same transaction, not after it by the
  // route. An install that succeeded and an audit that failed would leave rows
  // in a customer-facing script with nobody's name on them — and the route
  // cannot make that atomic from outside, which is why the attribution is a
  // parameter here rather than a second call there.
  await client.$transaction([
    ...(newPlaybooks.length ? [client.salesPlaybook.createMany({ data: newPlaybooks })] : []),
    ...(newObjections.length ? [client.salesObjection.createMany({ data: newObjections })] : []),
    client.platformAuditLog.create({
      data: {
        platformAdminId: adminId,
        action: "sales_playbook_defaults_installed",
        details: result,
      },
    }),
  ]);

  return result;
}
