// app/refer/[code]/page.js
//
// fieldquo.com/refer/sunsetinc — where a referral link lands.
//
// Server-rendered rather than fetched on the client, because this page's job
// is to be persuasive in the first half-second on a phone with one bar of
// signal. A skeleton that resolves into "Sunset Inc referred you" has already
// lost the visitor it was built for.
//
// The code is a slug, not a random token, on purpose: it's read aloud, typed
// off a business card, and printed on a van. Enumerability is fine — the worst
// case is discovering that a company uses FieldQuo, which their own link
// broadcasts anyway.

export const dynamic = "force-dynamic";

import Link from "next/link";
import { notFound } from "next/navigation";
import { findReferrer, REFEREE_BONUS_MONTHS } from "@/lib/referrals";
import { readableForeground } from "@/lib/brand/colour";
import { marketingMetadata } from "@/lib/marketing/metadata";

// The new company's signup bonus, written the way a person says it.
//
// The count was printed unconditionally — "Get your first 1 month free",
// "Claim 1 month free". Grammatically defensible, and it reads like a template
// nobody finished, on the one screen whose whole job is to look deliberate. At
// one, the number goes; above one it stays and the noun pluralises.
//
// Derived from REFEREE_BONUS_MONTHS rather than written out, so raising the
// bonus to three months changes every line on this page at once.
const FIRST_MONTHS_FREE =
  REFEREE_BONUS_MONTHS === 1
    ? "your first month free"
    : `your first ${REFEREE_BONUS_MONTHS} months free`;

export async function generateMetadata({ params }) {
  const { code } = await params;
  const referrer = await findReferrer(code);

  if (!referrer) return { title: "FieldQuo" };

  // Open Graph matters more here than on most pages — this link gets pasted
  // into WhatsApp and Facebook groups, where the preview card IS the pitch.
  const title = `${referrer.name} thinks you'd like FieldQuo`;
  const description = `Quotes, invoices and scheduling for field-service businesses. Get ${FIRST_MONTHS_FREE} when you sign up through ${referrer.name}.`;

  // marketingMetadata adds metadataBase, the canonical and og:url — without a
  // metadataBase the og:image generated by ../opengraph-image.js resolves
  // against localhost, which is invisible until someone shares a link.
  return marketingMetadata({
    path: `/refer/${encodeURIComponent(code)}`,
    title,
    description,
  });
}

export default async function ReferralLandingPage({ params }) {
  const { code } = await params;
  const referrer = await findReferrer(code);

  if (!referrer || referrer.onboardingStatus === "churned") notFound();

  // Normalised once so the background and the ink measured against it can
  // never be computed from two different values.
  const brandBg = referrer.brandColor || "#06356b";

  return (
    <div className="min-h-screen bg-[#f5f2ec] flex items-center justify-center px-4 py-12">
      <div className="max-w-lg w-full">
        <div className="bg-white border border-black/10 rounded-2xl overflow-hidden shadow-sm">
          <div className="px-7 py-8 text-center">
            {referrer.logoUrl ? (
              // eslint-disable-next-line @next/next/no-img-element
              <img
                src={referrer.logoUrl}
                alt={referrer.name}
                className="h-12 w-auto object-contain mx-auto mb-5"
              />
            ) : (
              // The referrer's initial, on the referrer's colour.
              //
              // The ink was hardcoded #2d2520 — the page's near-black — over
              // whatever hex the company chose. Measured: 1.24:1 on the
              // default #06356b, 1.16:1 on the tenant whose brand is #1a1a1a,
              // 1.27:1 on the dark-green one. The DEFAULT case was invisible,
              // so every referrer without a logo showed an empty coloured
              // square. readableForeground picks the better of black and white
              // against the actual colour, which is what the funnel and the
              // quote document already do.
              <div
                className="h-12 w-12 rounded-xl mx-auto mb-5 flex items-center justify-center text-lg font-bold"
                style={{
                  backgroundColor: brandBg,
                  color: readableForeground(brandBg),
                }}
              >
                {referrer.name.charAt(0).toUpperCase()}
              </div>
            )}

            <p className="text-sm text-[#2d2520]/60">
              {referrer.name} uses FieldQuo
            </p>
            <h1 className="text-2xl font-bold text-[#2d2520] mt-2 leading-tight">
              Get {FIRST_MONTHS_FREE}
            </h1>
            <p className="text-sm text-[#2d2520]/70 mt-3">
              Quotes, invoices, scheduling and payments for field-service
              businesses — built for people who&apos;d rather be on site than in
              a spreadsheet.
            </p>

            <Link
              href={`/signup?ref=${encodeURIComponent(referrer.referralCode)}`}
              className="mt-6 inline-block w-full bg-brand-accent text-brand-accent-foreground font-bold py-3.5 rounded-full"
            >
              Claim {FIRST_MONTHS_FREE}
            </Link>

            <p className="text-xs text-[#2d2520]/40 mt-3">
              No card charged during your trial. Cancel any time.
            </p>
          </div>

          <div className="px-7 py-5 bg-[#faf8f4] border-t border-black/5">
            <ul className="space-y-2 text-sm text-[#2d2520]/70">
              <li>Build a quote on site and send it before you leave</li>
              <li>Get paid online — straight to your own bank account</li>
              <li>Send quotes in your client&apos;s language</li>
            </ul>
          </div>
        </div>

        {/* Says the quiet part out loud so nobody wastes a signup finding out.
            The offer acquires new customers; it isn't a discount for people
            already paying. */}
        <p className="text-center text-xs text-[#2d2520]/40 mt-5">
          For businesses new to FieldQuo. Already have an account?{" "}
          <Link href="/login" className="underline">
            Sign in
          </Link>
          .
        </p>
      </div>
    </div>
  );
}
