// lib/designer/templateCopy.js
//
// The words printed ON a catalogue template (lib/designer/templateCatalog.js),
// in every language the app speaks.
//
// ── Why these are not in app/i18n/appMessages.js ───────────────────────────
//
// Those are interface strings, chosen by the person using the screen. These
// are the words that go out on a post under the contractor's name, so they
// are written in the COMPANY's language (Company.defaultLanguage) at the
// moment a template is applied — and then they are the design's own text,
// never re-translated. Non-negotiable #6 applied to a post: a thing keeps the
// language it was made in. A French-speaking owner and an English-speaking
// office manager applying the same template get the same post.
//
// ── What is sample copy and what is a placeholder ──────────────────────────
//
// Plain entries ("Free estimates") are generic trade copy anybody may post
// as-is — they state no fact about the company. `ph.*` entries are bracketed
// placeholders for things only the company knows: a review, a number, a
// licence, their town when it has never been entered. lib/designer/
// placeholders.js tags the objects carrying them, and both publish routes
// refuse while one is still on the design — a template must never put an
// invented review or statistic in front of the public.
//
// Tokens in braces are filled from the company's own row by
// lib/designer/templateFill.js; a token with no data behind it becomes the
// matching `ph.*` text, never a guess.

export const TEMPLATE_LANGUAGES = ["en", "fr", "es", "uk", "pa", "tl", "de", "zh", "it"];

const en = {
  before: "BEFORE",
  after: "AFTER",
  during: "DURING",
  swipe: "Swipe →",
  ctaEstimate: "Book your free estimate",
  ctaCall: "Call {phone}",
  ctaMessage: "Send us a message",
  justCompleted: "Just completed in {town}",
  justCompletedSub: "Another project finished. Yours could be next.",
  freeEstimate: "Free estimates",
  freeEstimateSub: "Tell us about your project and get a clear price. No obligation.",
  nowBooking: "Now booking {season} projects",
  nowBookingSub: "Get on the schedule before it fills up.",
  seasonalSpecial: "{season} special",
  promoSub: "For a limited time. Ask us for details.",
  limitedSlots: "Limited spots this month",
  limitedSlotsSub: "Book now to lock in your date.",
  whatWeDo: "What we do",
  nowServing: "Now serving",
  reviewTitle: "What our customers say",
  licensed: "Licensed & insured",
  licensedSub: "Your project is in safe hands.",
  warrantyTitle: "Workmanship warranty",
  warrantySub: "We stand behind our work.",
  yearsTitle: "In business",
  servingTown: "Serving {town} and nearby",
  milestoneTitle: "Projects completed",
  thankYouCustomers: "Thank you for trusting {company}.",
  signsTitle: "3 signs it's time to call a pro",
  checklistTitle: "Maintenance checklist",
  mythTitle: "Myth vs fact",
  myth: "MYTH",
  fact: "FACT",
  faqTitle: "Your questions, answered",
  q: "Q",
  a: "A",
  howTitle: "How it works",
  stepLabel: "Step {n}",
  step1: "Tell us about your project",
  step2: "Get a clear, written quote",
  step3: "We get to work and keep you posted",
  teamTitle: "Meet the team",
  hiringTitle: "We're hiring",
  hiringSub: "Send us a message to apply.",
  crewTitle: "Our crew at work",
  thanks: "Thank you!",
  thanksSub: "From all of us at {company}",
  referralTitle: "Know someone who needs a hand?",
  referralSub: "Send them our way.",
  spring: "Spring",
  summer: "Summer",
  fall: "Fall",
  winter: "Winter",
  "ph.town": "[Your town]",
  "ph.phone": "[Your phone number]",
  "ph.website": "[Your website]",
  "ph.areas": "[Towns you serve]",
  "ph.services": "[List your services]",
  "ph.review": "[Paste a real review from one of your customers]",
  "ph.reviewer": "[Customer name]",
  "ph.number": "[Number]",
  "ph.years": "[Number] years",
  "ph.offer": "[Your offer]",
  "ph.licence": "[Licence / insurance number]",
  "ph.sign": "[A sign to watch for]",
  "ph.task": "[A maintenance task]",
  "ph.myth": "[A common myth]",
  "ph.fact": "[The fact]",
  "ph.question": "[A question customers ask]",
  "ph.answer": "[Your answer]",
  "ph.name": "[Name]",
  "ph.role": "[Role]",
  "ph.hiringRole": "[The role you're hiring for]",
  "ph.reward": "[Your referral reward]",
  "ph.photo": "Add a photo",
  "ph.photoBefore": "Add a BEFORE photo",
  "ph.photoAfter": "Add an AFTER photo",
  "ph.photoDuring": "Add a DURING photo",
};

const fr = {
  before: "AVANT",
  after: "APRÈS",
  during: "PENDANT",
  swipe: "Faites défiler →",
  ctaEstimate: "Réservez votre estimation gratuite",
  ctaCall: "Appelez le {phone}",
  ctaMessage: "Écrivez-nous",
  justCompleted: "Projet terminé à {town}",
  justCompletedSub: "Un autre projet terminé. Le vôtre pourrait être le prochain.",
  freeEstimate: "Estimations gratuites",
  freeEstimateSub: "Parlez-nous de votre projet et obtenez un prix clair. Sans engagement.",
  nowBooking: "Réservations ouvertes : projets {season}",
  nowBookingSub: "Réservez votre place avant que l'horaire soit complet.",
  seasonalSpecial: "Offre {season}",
  promoSub: "Pour une durée limitée. Demandez-nous les détails.",
  limitedSlots: "Places limitées ce mois-ci",
  limitedSlotsSub: "Réservez maintenant pour garantir votre date.",
  whatWeDo: "Nos services",
  nowServing: "Nous desservons",
  reviewTitle: "Ce que disent nos clients",
  licensed: "Licencié et assuré",
  licensedSub: "Votre projet est entre de bonnes mains.",
  warrantyTitle: "Garantie sur la main-d'œuvre",
  warrantySub: "Nous garantissons notre travail.",
  yearsTitle: "En affaires",
  servingTown: "Au service de {town} et des environs",
  milestoneTitle: "Projets réalisés",
  thankYouCustomers: "Merci de faire confiance à {company}.",
  signsTitle: "3 signes qu'il est temps d'appeler un pro",
  checklistTitle: "Liste d'entretien",
  mythTitle: "Mythe ou réalité",
  myth: "MYTHE",
  fact: "RÉALITÉ",
  faqTitle: "Vos questions, nos réponses",
  q: "Q",
  a: "R",
  howTitle: "Comment ça marche",
  stepLabel: "Étape {n}",
  step1: "Parlez-nous de votre projet",
  step2: "Recevez une soumission claire et écrite",
  step3: "Nous nous mettons au travail et vous tenons informé",
  teamTitle: "Notre équipe",
  hiringTitle: "Nous embauchons",
  hiringSub: "Écrivez-nous pour postuler.",
  crewTitle: "Notre équipe à l'œuvre",
  thanks: "Merci !",
  thanksSub: "De toute l'équipe de {company}",
  referralTitle: "Vous connaissez quelqu'un qui a besoin d'un coup de main ?",
  referralSub: "Recommandez-nous.",
  spring: "printemps",
  summer: "été",
  fall: "automne",
  winter: "hiver",
  "ph.town": "[Votre ville]",
  "ph.phone": "[Votre numéro de téléphone]",
  "ph.website": "[Votre site web]",
  "ph.areas": "[Les villes que vous desservez]",
  "ph.services": "[La liste de vos services]",
  "ph.review": "[Collez un vrai avis d'un de vos clients]",
  "ph.reviewer": "[Nom du client]",
  "ph.number": "[Nombre]",
  "ph.years": "[Nombre] ans",
  "ph.offer": "[Votre offre]",
  "ph.licence": "[Numéro de licence / d'assurance]",
  "ph.sign": "[Un signe à surveiller]",
  "ph.task": "[Une tâche d'entretien]",
  "ph.myth": "[Un mythe répandu]",
  "ph.fact": "[La réalité]",
  "ph.question": "[Une question que posent vos clients]",
  "ph.answer": "[Votre réponse]",
  "ph.name": "[Nom]",
  "ph.role": "[Poste]",
  "ph.hiringRole": "[Le poste à pourvoir]",
  "ph.reward": "[Votre récompense de parrainage]",
  "ph.photo": "Ajoutez une photo",
  "ph.photoBefore": "Ajoutez une photo AVANT",
  "ph.photoAfter": "Ajoutez une photo APRÈS",
  "ph.photoDuring": "Ajoutez une photo PENDANT",
};

const es = {
  before: "ANTES",
  after: "DESPUÉS",
  during: "DURANTE",
  swipe: "Desliza →",
  ctaEstimate: "Reserva tu presupuesto gratis",
  ctaCall: "Llama al {phone}",
  ctaMessage: "Envíanos un mensaje",
  justCompleted: "Recién terminado en {town}",
  justCompletedSub: "Otro proyecto terminado. El tuyo podría ser el siguiente.",
  freeEstimate: "Presupuestos gratis",
  freeEstimateSub: "Cuéntanos tu proyecto y recibe un precio claro. Sin compromiso.",
  nowBooking: "Reservando proyectos de {season}",
  nowBookingSub: "Asegura tu lugar antes de que se llene la agenda.",
  seasonalSpecial: "Especial de {season}",
  promoSub: "Por tiempo limitado. Pregúntanos los detalles.",
  limitedSlots: "Plazas limitadas este mes",
  limitedSlotsSub: "Reserva ya para asegurar tu fecha.",
  whatWeDo: "Lo que hacemos",
  nowServing: "Damos servicio en",
  reviewTitle: "Lo que dicen nuestros clientes",
  licensed: "Con licencia y seguro",
  licensedSub: "Tu proyecto está en buenas manos.",
  warrantyTitle: "Garantía de mano de obra",
  warrantySub: "Respaldamos nuestro trabajo.",
  yearsTitle: "En el negocio",
  servingTown: "Al servicio de {town} y alrededores",
  milestoneTitle: "Proyectos completados",
  thankYouCustomers: "Gracias por confiar en {company}.",
  signsTitle: "3 señales de que es hora de llamar a un profesional",
  checklistTitle: "Lista de mantenimiento",
  mythTitle: "Mito o realidad",
  myth: "MITO",
  fact: "REALIDAD",
  faqTitle: "Tus preguntas, respondidas",
  q: "P",
  a: "R",
  howTitle: "Cómo funciona",
  stepLabel: "Paso {n}",
  step1: "Cuéntanos tu proyecto",
  step2: "Recibe un presupuesto claro y por escrito",
  step3: "Nos ponemos manos a la obra y te mantenemos informado",
  teamTitle: "Conoce al equipo",
  hiringTitle: "Estamos contratando",
  hiringSub: "Envíanos un mensaje para postularte.",
  crewTitle: "Nuestro equipo en acción",
  thanks: "¡Gracias!",
  thanksSub: "De parte de todos en {company}",
  referralTitle: "¿Conoces a alguien que necesite una mano?",
  referralSub: "Recomiéndanos.",
  spring: "primavera",
  summer: "verano",
  fall: "otoño",
  winter: "invierno",
  "ph.town": "[Tu ciudad]",
  "ph.phone": "[Tu número de teléfono]",
  "ph.website": "[Tu sitio web]",
  "ph.areas": "[Las zonas que atiendes]",
  "ph.services": "[Lista tus servicios]",
  "ph.review": "[Pega una reseña real de uno de tus clientes]",
  "ph.reviewer": "[Nombre del cliente]",
  "ph.number": "[Número]",
  "ph.years": "[Número] años",
  "ph.offer": "[Tu oferta]",
  "ph.licence": "[Número de licencia / seguro]",
  "ph.sign": "[Una señal a vigilar]",
  "ph.task": "[Una tarea de mantenimiento]",
  "ph.myth": "[Un mito común]",
  "ph.fact": "[La realidad]",
  "ph.question": "[Una pregunta que hacen los clientes]",
  "ph.answer": "[Tu respuesta]",
  "ph.name": "[Nombre]",
  "ph.role": "[Puesto]",
  "ph.hiringRole": "[El puesto que buscas]",
  "ph.reward": "[Tu recompensa por recomendación]",
  "ph.photo": "Añade una foto",
  "ph.photoBefore": "Añade una foto de ANTES",
  "ph.photoAfter": "Añade una foto de DESPUÉS",
  "ph.photoDuring": "Añade una foto de DURANTE",
};

const uk = {
  before: "ДО",
  after: "ПІСЛЯ",
  during: "ПІД ЧАС",
  swipe: "Гортайте →",
  ctaEstimate: "Замовте безкоштовний кошторис",
  ctaCall: "Телефонуйте: {phone}",
  ctaMessage: "Напишіть нам",
  justCompleted: "Щойно завершено в {town}",
  justCompletedSub: "Ще один проєкт завершено. Наступним може бути ваш.",
  freeEstimate: "Безкоштовні кошториси",
  freeEstimateSub: "Розкажіть про свій проєкт і отримайте чітку ціну. Без зобов'язань.",
  nowBooking: "Приймаємо замовлення на сезон: {season}",
  nowBookingSub: "Запишіться, поки графік не заповнився.",
  seasonalSpecial: "Сезонна пропозиція: {season}",
  promoSub: "Обмежений час. Запитайте нас про деталі.",
  limitedSlots: "Цього місяця кількість місць обмежена",
  limitedSlotsSub: "Бронюйте зараз, щоб закріпити дату.",
  whatWeDo: "Що ми робимо",
  nowServing: "Працюємо в",
  reviewTitle: "Що кажуть наші клієнти",
  licensed: "Ліцензовані та застраховані",
  licensedSub: "Ваш проєкт у надійних руках.",
  warrantyTitle: "Гарантія на роботу",
  warrantySub: "Ми відповідаємо за свою роботу.",
  yearsTitle: "На ринку",
  servingTown: "Працюємо в {town} та околицях",
  milestoneTitle: "Завершених проєктів",
  thankYouCustomers: "Дякуємо, що довіряєте {company}.",
  signsTitle: "3 ознаки, що час кликати фахівця",
  checklistTitle: "Список обслуговування",
  mythTitle: "Міф чи факт",
  myth: "МІФ",
  fact: "ФАКТ",
  faqTitle: "Відповіді на ваші запитання",
  q: "П",
  a: "В",
  howTitle: "Як це працює",
  stepLabel: "Крок {n}",
  step1: "Розкажіть нам про свій проєкт",
  step2: "Отримайте чіткий письмовий кошторис",
  step3: "Ми беремося до роботи й тримаємо вас у курсі",
  teamTitle: "Знайомтеся з командою",
  hiringTitle: "Ми наймаємо",
  hiringSub: "Напишіть нам, щоб подати заявку.",
  crewTitle: "Наша бригада за роботою",
  thanks: "Дякуємо!",
  thanksSub: "Від усієї команди {company}",
  referralTitle: "Знаєте когось, кому потрібна допомога?",
  referralSub: "Порекомендуйте нас.",
  spring: "весна",
  summer: "літо",
  fall: "осінь",
  winter: "зима",
  "ph.town": "[Ваше місто]",
  "ph.phone": "[Ваш номер телефону]",
  "ph.website": "[Ваш вебсайт]",
  "ph.areas": "[Міста, де ви працюєте]",
  "ph.services": "[Перелік ваших послуг]",
  "ph.review": "[Вставте справжній відгук одного з ваших клієнтів]",
  "ph.reviewer": "[Ім'я клієнта]",
  "ph.number": "[Число]",
  "ph.years": "[Число] років",
  "ph.offer": "[Ваша пропозиція]",
  "ph.licence": "[Номер ліцензії / страховки]",
  "ph.sign": "[Ознака, на яку варто зважати]",
  "ph.task": "[Завдання з обслуговування]",
  "ph.myth": "[Поширений міф]",
  "ph.fact": "[Факт]",
  "ph.question": "[Запитання, яке ставлять клієнти]",
  "ph.answer": "[Ваша відповідь]",
  "ph.name": "[Ім'я]",
  "ph.role": "[Посада]",
  "ph.hiringRole": "[Посада, на яку ви шукаєте людину]",
  "ph.reward": "[Ваша винагорода за рекомендацію]",
  "ph.photo": "Додайте фото",
  "ph.photoBefore": "Додайте фото ДО",
  "ph.photoAfter": "Додайте фото ПІСЛЯ",
  "ph.photoDuring": "Додайте фото ПІД ЧАС",
};

const pa = {
  before: "ਪਹਿਲਾਂ",
  after: "ਬਾਅਦ",
  during: "ਦੌਰਾਨ",
  swipe: "ਸਵਾਈਪ ਕਰੋ →",
  ctaEstimate: "ਆਪਣਾ ਮੁਫ਼ਤ ਅੰਦਾਜ਼ਾ ਬੁੱਕ ਕਰੋ",
  ctaCall: "ਕਾਲ ਕਰੋ: {phone}",
  ctaMessage: "ਸਾਨੂੰ ਸੁਨੇਹਾ ਭੇਜੋ",
  justCompleted: "{town} ਵਿੱਚ ਹੁਣੇ ਪੂਰਾ ਕੀਤਾ",
  justCompletedSub: "ਇੱਕ ਹੋਰ ਪ੍ਰੋਜੈਕਟ ਪੂਰਾ। ਅਗਲਾ ਤੁਹਾਡਾ ਹੋ ਸਕਦਾ ਹੈ।",
  freeEstimate: "ਮੁਫ਼ਤ ਅੰਦਾਜ਼ੇ",
  freeEstimateSub: "ਸਾਨੂੰ ਆਪਣੇ ਪ੍ਰੋਜੈਕਟ ਬਾਰੇ ਦੱਸੋ ਅਤੇ ਸਾਫ਼ ਕੀਮਤ ਲਵੋ। ਕੋਈ ਜ਼ਿੰਮੇਵਾਰੀ ਨਹੀਂ।",
  nowBooking: "{season} ਦੇ ਪ੍ਰੋਜੈਕਟਾਂ ਲਈ ਬੁਕਿੰਗ ਜਾਰੀ",
  nowBookingSub: "ਸਮਾਂ-ਸਾਰਣੀ ਭਰਨ ਤੋਂ ਪਹਿਲਾਂ ਆਪਣੀ ਥਾਂ ਲਵੋ।",
  seasonalSpecial: "{season} ਦੀ ਖ਼ਾਸ ਪੇਸ਼ਕਸ਼",
  promoSub: "ਸੀਮਤ ਸਮੇਂ ਲਈ। ਵੇਰਵਿਆਂ ਲਈ ਸਾਨੂੰ ਪੁੱਛੋ।",
  limitedSlots: "ਇਸ ਮਹੀਨੇ ਸੀਮਤ ਥਾਵਾਂ",
  limitedSlotsSub: "ਆਪਣੀ ਤਾਰੀਖ਼ ਪੱਕੀ ਕਰਨ ਲਈ ਹੁਣੇ ਬੁੱਕ ਕਰੋ।",
  whatWeDo: "ਅਸੀਂ ਕੀ ਕਰਦੇ ਹਾਂ",
  nowServing: "ਹੁਣ ਸੇਵਾ ਦੇ ਰਹੇ ਹਾਂ",
  reviewTitle: "ਸਾਡੇ ਗਾਹਕ ਕੀ ਕਹਿੰਦੇ ਹਨ",
  licensed: "ਲਾਇਸੈਂਸਸ਼ੁਦਾ ਅਤੇ ਬੀਮਾਸ਼ੁਦਾ",
  licensedSub: "ਤੁਹਾਡਾ ਪ੍ਰੋਜੈਕਟ ਸੁਰੱਖਿਅਤ ਹੱਥਾਂ ਵਿੱਚ ਹੈ।",
  warrantyTitle: "ਕੰਮ ਦੀ ਵਾਰੰਟੀ",
  warrantySub: "ਅਸੀਂ ਆਪਣੇ ਕੰਮ ਦੀ ਜ਼ਿੰਮੇਵਾਰੀ ਲੈਂਦੇ ਹਾਂ।",
  yearsTitle: "ਕਾਰੋਬਾਰ ਵਿੱਚ",
  servingTown: "{town} ਅਤੇ ਆਲੇ-ਦੁਆਲੇ ਸੇਵਾ",
  milestoneTitle: "ਪੂਰੇ ਕੀਤੇ ਪ੍ਰੋਜੈਕਟ",
  thankYouCustomers: "{company} 'ਤੇ ਭਰੋਸਾ ਕਰਨ ਲਈ ਧੰਨਵਾਦ।",
  signsTitle: "3 ਨਿਸ਼ਾਨੀਆਂ ਕਿ ਮਾਹਰ ਨੂੰ ਬੁਲਾਉਣ ਦਾ ਸਮਾਂ ਹੈ",
  checklistTitle: "ਦੇਖਭਾਲ ਦੀ ਸੂਚੀ",
  mythTitle: "ਮਿੱਥ ਬਨਾਮ ਸੱਚ",
  myth: "ਮਿੱਥ",
  fact: "ਸੱਚ",
  faqTitle: "ਤੁਹਾਡੇ ਸਵਾਲਾਂ ਦੇ ਜਵਾਬ",
  q: "ਸ",
  a: "ਜ",
  howTitle: "ਇਹ ਕਿਵੇਂ ਕੰਮ ਕਰਦਾ ਹੈ",
  stepLabel: "ਕਦਮ {n}",
  step1: "ਸਾਨੂੰ ਆਪਣੇ ਪ੍ਰੋਜੈਕਟ ਬਾਰੇ ਦੱਸੋ",
  step2: "ਸਾਫ਼, ਲਿਖਤੀ ਕੋਟ ਲਵੋ",
  step3: "ਅਸੀਂ ਕੰਮ ਸ਼ੁਰੂ ਕਰਦੇ ਹਾਂ ਅਤੇ ਤੁਹਾਨੂੰ ਜਾਣੂ ਰੱਖਦੇ ਹਾਂ",
  teamTitle: "ਟੀਮ ਨੂੰ ਮਿਲੋ",
  hiringTitle: "ਅਸੀਂ ਭਰਤੀ ਕਰ ਰਹੇ ਹਾਂ",
  hiringSub: "ਅਰਜ਼ੀ ਦੇਣ ਲਈ ਸਾਨੂੰ ਸੁਨੇਹਾ ਭੇਜੋ।",
  crewTitle: "ਕੰਮ ਕਰਦੀ ਸਾਡੀ ਟੀਮ",
  thanks: "ਧੰਨਵਾਦ!",
  thanksSub: "{company} ਦੀ ਪੂਰੀ ਟੀਮ ਵੱਲੋਂ",
  referralTitle: "ਕਿਸੇ ਨੂੰ ਜਾਣਦੇ ਹੋ ਜਿਸ ਨੂੰ ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
  referralSub: "ਉਨ੍ਹਾਂ ਨੂੰ ਸਾਡੇ ਕੋਲ ਭੇਜੋ।",
  spring: "ਬਸੰਤ",
  summer: "ਗਰਮੀ",
  fall: "ਪਤਝੜ",
  winter: "ਸਰਦੀ",
  "ph.town": "[ਤੁਹਾਡਾ ਸ਼ਹਿਰ]",
  "ph.phone": "[ਤੁਹਾਡਾ ਫ਼ੋਨ ਨੰਬਰ]",
  "ph.website": "[ਤੁਹਾਡੀ ਵੈੱਬਸਾਈਟ]",
  "ph.areas": "[ਜਿਨ੍ਹਾਂ ਸ਼ਹਿਰਾਂ ਵਿੱਚ ਤੁਸੀਂ ਸੇਵਾ ਦਿੰਦੇ ਹੋ]",
  "ph.services": "[ਆਪਣੀਆਂ ਸੇਵਾਵਾਂ ਲਿਖੋ]",
  "ph.review": "[ਆਪਣੇ ਕਿਸੇ ਗਾਹਕ ਦੀ ਅਸਲ ਸਮੀਖਿਆ ਇੱਥੇ ਪਾਓ]",
  "ph.reviewer": "[ਗਾਹਕ ਦਾ ਨਾਮ]",
  "ph.number": "[ਗਿਣਤੀ]",
  "ph.years": "[ਗਿਣਤੀ] ਸਾਲ",
  "ph.offer": "[ਤੁਹਾਡੀ ਪੇਸ਼ਕਸ਼]",
  "ph.licence": "[ਲਾਇਸੈਂਸ / ਬੀਮਾ ਨੰਬਰ]",
  "ph.sign": "[ਧਿਆਨ ਰੱਖਣ ਵਾਲੀ ਨਿਸ਼ਾਨੀ]",
  "ph.task": "[ਦੇਖਭਾਲ ਦਾ ਇੱਕ ਕੰਮ]",
  "ph.myth": "[ਇੱਕ ਆਮ ਮਿੱਥ]",
  "ph.fact": "[ਸੱਚ]",
  "ph.question": "[ਗਾਹਕਾਂ ਦਾ ਇੱਕ ਸਵਾਲ]",
  "ph.answer": "[ਤੁਹਾਡਾ ਜਵਾਬ]",
  "ph.name": "[ਨਾਮ]",
  "ph.role": "[ਅਹੁਦਾ]",
  "ph.hiringRole": "[ਜਿਸ ਅਹੁਦੇ ਲਈ ਭਰਤੀ ਕਰ ਰਹੇ ਹੋ]",
  "ph.reward": "[ਸਿਫ਼ਾਰਸ਼ ਦਾ ਤੁਹਾਡਾ ਇਨਾਮ]",
  "ph.photo": "ਇੱਕ ਫ਼ੋਟੋ ਜੋੜੋ",
  "ph.photoBefore": "ਪਹਿਲਾਂ ਵਾਲੀ ਫ਼ੋਟੋ ਜੋੜੋ",
  "ph.photoAfter": "ਬਾਅਦ ਵਾਲੀ ਫ਼ੋਟੋ ਜੋੜੋ",
  "ph.photoDuring": "ਦੌਰਾਨ ਵਾਲੀ ਫ਼ੋਟੋ ਜੋੜੋ",
};

const tl = {
  before: "BAGO",
  after: "PAGKATAPOS",
  during: "HABANG GINAGAWA",
  swipe: "I-swipe →",
  ctaEstimate: "Mag-book ng libreng estimate",
  ctaCall: "Tumawag sa {phone}",
  ctaMessage: "Padalhan kami ng mensahe",
  justCompleted: "Katatapos lang sa {town}",
  justCompletedSub: "Isa na namang proyektong tapos. Baka ikaw na ang susunod.",
  freeEstimate: "Libreng estimate",
  freeEstimateSub: "Ikuwento ang proyekto mo at kumuha ng malinaw na presyo. Walang obligasyon.",
  nowBooking: "Tumatanggap na ng mga proyekto ngayong {season}",
  nowBookingSub: "Magpa-iskedyul bago mapuno.",
  seasonalSpecial: "Espesyal ngayong {season}",
  promoSub: "Sa limitadong panahon. Magtanong sa amin para sa detalye.",
  limitedSlots: "Limitado ang slot ngayong buwan",
  limitedSlotsSub: "Mag-book na para makuha ang petsa mo.",
  whatWeDo: "Ang aming ginagawa",
  nowServing: "Naglilingkod na sa",
  reviewTitle: "Sabi ng aming mga customer",
  licensed: "Lisensyado at insured",
  licensedSub: "Nasa mabuting kamay ang proyekto mo.",
  warrantyTitle: "Warranty sa pagkakagawa",
  warrantySub: "Pinaninindigan namin ang aming trabaho.",
  yearsTitle: "Sa negosyo",
  servingTown: "Naglilingkod sa {town} at kalapit",
  milestoneTitle: "Mga natapos na proyekto",
  thankYouCustomers: "Salamat sa pagtitiwala sa {company}.",
  signsTitle: "3 senyales na oras nang tumawag ng eksperto",
  checklistTitle: "Checklist sa maintenance",
  mythTitle: "Mito o totoo",
  myth: "MITO",
  fact: "TOTOO",
  faqTitle: "Sagot sa inyong mga tanong",
  q: "T",
  a: "S",
  howTitle: "Paano ito gumagana",
  stepLabel: "Hakbang {n}",
  step1: "Ikuwento sa amin ang proyekto mo",
  step2: "Kumuha ng malinaw at nakasulat na quote",
  step3: "Sisimulan namin ang trabaho at ia-update ka namin",
  teamTitle: "Kilalanin ang team",
  hiringTitle: "Naghahanap kami ng tauhan",
  hiringSub: "Padalhan kami ng mensahe para mag-apply.",
  crewTitle: "Ang aming crew habang nagtatrabaho",
  thanks: "Salamat!",
  thanksSub: "Mula sa aming lahat sa {company}",
  referralTitle: "May kilala ka bang nangangailangan ng tulong?",
  referralSub: "Irekomenda kami sa kanila.",
  spring: "tagsibol",
  summer: "tag-init",
  fall: "taglagas",
  winter: "taglamig",
  "ph.town": "[Ang iyong bayan]",
  "ph.phone": "[Ang iyong numero ng telepono]",
  "ph.website": "[Ang iyong website]",
  "ph.areas": "[Mga bayang pinaglilingkuran mo]",
  "ph.services": "[Ilista ang iyong mga serbisyo]",
  "ph.review": "[Ilagay ang totoong review ng isa sa iyong mga customer]",
  "ph.reviewer": "[Pangalan ng customer]",
  "ph.number": "[Bilang]",
  "ph.years": "[Bilang] taon",
  "ph.offer": "[Ang iyong alok]",
  "ph.licence": "[Numero ng lisensya / insurance]",
  "ph.sign": "[Isang senyales na dapat bantayan]",
  "ph.task": "[Isang gawain sa maintenance]",
  "ph.myth": "[Isang karaniwang mito]",
  "ph.fact": "[Ang totoo]",
  "ph.question": "[Isang tanong ng mga customer]",
  "ph.answer": "[Ang iyong sagot]",
  "ph.name": "[Pangalan]",
  "ph.role": "[Posisyon]",
  "ph.hiringRole": "[Ang posisyong hinahanapan mo]",
  "ph.reward": "[Ang iyong gantimpala sa referral]",
  "ph.photo": "Magdagdag ng litrato",
  "ph.photoBefore": "Magdagdag ng litratong BAGO",
  "ph.photoAfter": "Magdagdag ng litratong PAGKATAPOS",
  "ph.photoDuring": "Magdagdag ng litratong HABANG GINAGAWA",
};

const de = {
  before: "VORHER",
  after: "NACHHER",
  during: "WÄHRENDDESSEN",
  swipe: "Wischen →",
  ctaEstimate: "Kostenlosen Kostenvoranschlag buchen",
  ctaCall: "Anrufen: {phone}",
  ctaMessage: "Schreiben Sie uns",
  justCompleted: "Gerade fertiggestellt in {town}",
  justCompletedSub: "Wieder ein Projekt abgeschlossen. Ihres könnte das nächste sein.",
  freeEstimate: "Kostenlose Kostenvoranschläge",
  freeEstimateSub: "Erzählen Sie uns von Ihrem Projekt und erhalten Sie einen klaren Preis. Unverbindlich.",
  nowBooking: "Jetzt Termine für {season} buchen",
  nowBookingSub: "Sichern Sie sich einen Platz, bevor der Kalender voll ist.",
  seasonalSpecial: "{season}-Angebot",
  promoSub: "Nur für kurze Zeit. Fragen Sie uns nach Details.",
  limitedSlots: "Diesen Monat nur wenige Termine frei",
  limitedSlotsSub: "Jetzt buchen und Ihren Termin sichern.",
  whatWeDo: "Unsere Leistungen",
  nowServing: "Jetzt im Einsatz in",
  reviewTitle: "Das sagen unsere Kunden",
  licensed: "Zugelassen und versichert",
  licensedSub: "Ihr Projekt ist in guten Händen.",
  warrantyTitle: "Garantie auf die Ausführung",
  warrantySub: "Wir stehen zu unserer Arbeit.",
  yearsTitle: "Im Geschäft",
  servingTown: "Für {town} und Umgebung",
  milestoneTitle: "Abgeschlossene Projekte",
  thankYouCustomers: "Danke für Ihr Vertrauen in {company}.",
  signsTitle: "3 Zeichen, dass es Zeit für einen Profi ist",
  checklistTitle: "Wartungs-Checkliste",
  mythTitle: "Mythos oder Fakt",
  myth: "MYTHOS",
  fact: "FAKT",
  faqTitle: "Ihre Fragen, beantwortet",
  q: "F",
  a: "A",
  howTitle: "So funktioniert's",
  stepLabel: "Schritt {n}",
  step1: "Erzählen Sie uns von Ihrem Projekt",
  step2: "Sie erhalten ein klares, schriftliches Angebot",
  step3: "Wir legen los und halten Sie auf dem Laufenden",
  teamTitle: "Unser Team",
  hiringTitle: "Wir stellen ein",
  hiringSub: "Schreiben Sie uns, um sich zu bewerben.",
  crewTitle: "Unser Team bei der Arbeit",
  thanks: "Danke!",
  thanksSub: "Vom ganzen Team von {company}",
  referralTitle: "Kennen Sie jemanden, der Hilfe braucht?",
  referralSub: "Empfehlen Sie uns weiter.",
  spring: "Frühling",
  summer: "Sommer",
  fall: "Herbst",
  winter: "Winter",
  "ph.town": "[Ihr Ort]",
  "ph.phone": "[Ihre Telefonnummer]",
  "ph.website": "[Ihre Website]",
  "ph.areas": "[Orte, in denen Sie arbeiten]",
  "ph.services": "[Ihre Leistungen]",
  "ph.review": "[Fügen Sie eine echte Bewertung eines Kunden ein]",
  "ph.reviewer": "[Name des Kunden]",
  "ph.number": "[Zahl]",
  "ph.years": "[Zahl] Jahre",
  "ph.offer": "[Ihr Angebot]",
  "ph.licence": "[Zulassungs- / Versicherungsnummer]",
  "ph.sign": "[Ein Warnzeichen]",
  "ph.task": "[Eine Wartungsaufgabe]",
  "ph.myth": "[Ein verbreiteter Mythos]",
  "ph.fact": "[Der Fakt]",
  "ph.question": "[Eine Frage, die Kunden stellen]",
  "ph.answer": "[Ihre Antwort]",
  "ph.name": "[Name]",
  "ph.role": "[Funktion]",
  "ph.hiringRole": "[Die Stelle, die Sie besetzen]",
  "ph.reward": "[Ihre Empfehlungsprämie]",
  "ph.photo": "Foto hinzufügen",
  "ph.photoBefore": "VORHER-Foto hinzufügen",
  "ph.photoAfter": "NACHHER-Foto hinzufügen",
  "ph.photoDuring": "Foto WÄHRENDDESSEN hinzufügen",
};

const zh = {
  before: "施工前",
  after: "施工后",
  during: "施工中",
  swipe: "向左滑动 →",
  ctaEstimate: "预约免费估价",
  ctaCall: "致电 {phone}",
  ctaMessage: "给我们留言",
  justCompleted: "{town} 刚刚完工",
  justCompletedSub: "又一个项目完工。下一个可能就是您的。",
  freeEstimate: "免费估价",
  freeEstimateSub: "告诉我们您的项目，获取清晰报价。无任何义务。",
  nowBooking: "{season}项目现正接受预约",
  nowBookingSub: "档期排满前，快来预约。",
  seasonalSpecial: "{season}特惠",
  promoSub: "限时优惠。详情请咨询我们。",
  limitedSlots: "本月名额有限",
  limitedSlotsSub: "立即预约，锁定您的日期。",
  whatWeDo: "我们的服务",
  nowServing: "服务区域",
  reviewTitle: "客户怎么说",
  licensed: "持牌并投保",
  licensedSub: "您的项目交给我们，尽可放心。",
  warrantyTitle: "施工质保",
  warrantySub: "我们对自己的工作负责。",
  yearsTitle: "从业",
  servingTown: "服务 {town} 及周边",
  milestoneTitle: "已完成项目",
  thankYouCustomers: "感谢您对 {company} 的信任。",
  signsTitle: "该请专业人士的 3 个信号",
  checklistTitle: "保养清单",
  mythTitle: "误区与事实",
  myth: "误区",
  fact: "事实",
  faqTitle: "为您解答常见问题",
  q: "问",
  a: "答",
  howTitle: "服务流程",
  stepLabel: "第 {n} 步",
  step1: "告诉我们您的项目",
  step2: "获取清晰的书面报价",
  step3: "我们开工，并随时向您通报进度",
  teamTitle: "认识我们的团队",
  hiringTitle: "我们正在招聘",
  hiringSub: "给我们留言即可申请。",
  crewTitle: "我们的团队在工作",
  thanks: "谢谢！",
  thanksSub: "{company} 全体同仁敬上",
  referralTitle: "认识需要帮忙的人吗？",
  referralSub: "欢迎推荐给我们。",
  spring: "春季",
  summer: "夏季",
  fall: "秋季",
  winter: "冬季",
  "ph.town": "[您所在的城镇]",
  "ph.phone": "[您的电话号码]",
  "ph.website": "[您的网站]",
  "ph.areas": "[您服务的城镇]",
  "ph.services": "[列出您的服务]",
  "ph.review": "[粘贴一位客户的真实评价]",
  "ph.reviewer": "[客户姓名]",
  "ph.number": "[数字]",
  "ph.years": "[数字] 年",
  "ph.offer": "[您的优惠]",
  "ph.licence": "[执照 / 保险编号]",
  "ph.sign": "[需要留意的信号]",
  "ph.task": "[一项保养工作]",
  "ph.myth": "[一个常见误区]",
  "ph.fact": "[事实]",
  "ph.question": "[客户常问的问题]",
  "ph.answer": "[您的回答]",
  "ph.name": "[姓名]",
  "ph.role": "[职位]",
  "ph.hiringRole": "[招聘的职位]",
  "ph.reward": "[您的推荐奖励]",
  "ph.photo": "添加照片",
  "ph.photoBefore": "添加施工前照片",
  "ph.photoAfter": "添加施工后照片",
  "ph.photoDuring": "添加施工中照片",
};

const it = {
  before: "PRIMA",
  after: "DOPO",
  during: "DURANTE",
  swipe: "Scorri →",
  ctaEstimate: "Prenota il tuo preventivo gratuito",
  ctaCall: "Chiama il {phone}",
  ctaMessage: "Scrivici un messaggio",
  justCompleted: "Appena completato a {town}",
  justCompletedSub: "Un altro progetto finito. Il prossimo potrebbe essere il tuo.",
  freeEstimate: "Preventivi gratuiti",
  freeEstimateSub: "Raccontaci il tuo progetto e ricevi un prezzo chiaro. Senza impegno.",
  nowBooking: "Prenotazioni aperte: progetti di {season}",
  nowBookingSub: "Fissa il tuo posto prima che l'agenda si riempia.",
  seasonalSpecial: "Offerta di {season}",
  promoSub: "Per un periodo limitato. Chiedici i dettagli.",
  limitedSlots: "Posti limitati questo mese",
  limitedSlotsSub: "Prenota ora per bloccare la tua data.",
  whatWeDo: "Cosa facciamo",
  nowServing: "Operiamo a",
  reviewTitle: "Cosa dicono i nostri clienti",
  licensed: "Abilitati e assicurati",
  licensedSub: "Il tuo progetto è in buone mani.",
  warrantyTitle: "Garanzia sulla lavorazione",
  warrantySub: "Garantiamo il nostro lavoro.",
  yearsTitle: "In attività",
  servingTown: "Al servizio di {town} e dintorni",
  milestoneTitle: "Progetti completati",
  thankYouCustomers: "Grazie per aver scelto {company}.",
  signsTitle: "3 segnali che è ora di chiamare un professionista",
  checklistTitle: "Lista di manutenzione",
  mythTitle: "Mito o realtà",
  myth: "MITO",
  fact: "REALTÀ",
  faqTitle: "Le tue domande, le nostre risposte",
  q: "D",
  a: "R",
  howTitle: "Come funziona",
  stepLabel: "Passo {n}",
  step1: "Raccontaci il tuo progetto",
  step2: "Ricevi un preventivo chiaro e scritto",
  step3: "Ci mettiamo al lavoro e ti teniamo aggiornato",
  teamTitle: "Conosci la squadra",
  hiringTitle: "Stiamo assumendo",
  hiringSub: "Scrivici un messaggio per candidarti.",
  crewTitle: "La nostra squadra al lavoro",
  thanks: "Grazie!",
  thanksSub: "Da tutti noi di {company}",
  referralTitle: "Conosci qualcuno che ha bisogno di una mano?",
  referralSub: "Consigliaci.",
  spring: "primavera",
  summer: "estate",
  fall: "autunno",
  winter: "inverno",
  "ph.town": "[La tua città]",
  "ph.phone": "[Il tuo numero di telefono]",
  "ph.website": "[Il tuo sito web]",
  "ph.areas": "[Le zone in cui lavori]",
  "ph.services": "[Elenca i tuoi servizi]",
  "ph.review": "[Incolla una recensione vera di un tuo cliente]",
  "ph.reviewer": "[Nome del cliente]",
  "ph.number": "[Numero]",
  "ph.years": "[Numero] anni",
  "ph.offer": "[La tua offerta]",
  "ph.licence": "[Numero di abilitazione / assicurazione]",
  "ph.sign": "[Un segnale da tenere d'occhio]",
  "ph.task": "[Un intervento di manutenzione]",
  "ph.myth": "[Un mito diffuso]",
  "ph.fact": "[La realtà]",
  "ph.question": "[Una domanda dei clienti]",
  "ph.answer": "[La tua risposta]",
  "ph.name": "[Nome]",
  "ph.role": "[Ruolo]",
  "ph.hiringRole": "[Il ruolo che cerchi]",
  "ph.reward": "[Il tuo premio per chi ci consiglia]",
  "ph.photo": "Aggiungi una foto",
  "ph.photoBefore": "Aggiungi una foto PRIMA",
  "ph.photoAfter": "Aggiungi una foto DOPO",
  "ph.photoDuring": "Aggiungi una foto DURANTE",
};

export const TEMPLATE_COPY = { en, fr, es, uk, pa, tl, de, zh, it };

/** A language this module has, else English — never a blank string. */
export function copyLanguage(language) {
  const code = String(language || "en").toLowerCase().slice(0, 2);
  return Object.prototype.hasOwnProperty.call(TEMPLATE_COPY, code) ? code : "en";
}

/** One string, in `language`, falling back to English for a missing key. */
export function copyFor(key, language) {
  const dict = TEMPLATE_COPY[copyLanguage(language)];
  return (dict && dict[key]) || en[key] || "";
}
