// lib/help/chrome.js
//
// The help centre's CHROME — nav, category names, buttons, notices — in every
// language the app speaks (the nine of app/i18n/appMessages.js).
//
// ── Why its own catalogue and not app.* keys ───────────────────────────────
//
// The bodies of articles exist in English, French and Spanish (written, not
// machine-translated — see content/help/). A Ukrainian or Punjabi reader
// still gets the whole frame in their language plus an honest one-line
// notice that the article itself is English for now; that frame is what this
// file carries. It is kept beside the help centre rather than inside
// app/i18n/appMessages.js because the help centre is a PUBLIC surface
// rendered on the server with no LanguageProvider, and because appMessages
// is the /app interface catalogue, gated by its own coverage floors — a
// separate surface's strings belong in a separate file that
// scripts/check-help-centre.mjs holds to the same rule: every key, every
// language, no English fallback that goes unreported.
//
// Every language block must carry every key `en` has; the check fails
// otherwise. A missing key would silently fall back to English, which is the
// exact "control that appears to work" AGENTS.md warns about.

const en = {
  "title": "Help Centre",
  "tagline": "Step-by-step guides for everything in FieldQuo — quotes, jobs, invoices, getting paid, your team, your website, and using it on your phone.",
  "search.placeholder": "Search the help centre…",
  "search.label": "Search",
  "search.none": "No articles match “{q}”.",
  "search.count": "{n} results for “{q}”",
  "home.browse": "Browse by topic",
  "home.popular": "Popular articles",
  "home.videos": "Videos",
  "home.count": "{n} articles",
  "nav.home": "Help centre",
  "nav.signIn": "Sign in",
  "nav.openApp": "Open FieldQuo",
  "nav.contact": "Contact support",
  "nav.language": "Language",
  "nav.theme": "Switch theme",
  "nav.menu": "Menu",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "Help",
  "article.onThisPage": "In this article",
  "article.updated": "Updated {date}",
  "article.related": "Related articles",
  "article.helpful": "Was this helpful?",
  "article.yes": "Yes",
  "article.no": "No",
  "article.thanks": "Thanks — noted.",
  "article.feedbackFailed": "Could not send that just now.",
  "article.prev": "Previous",
  "article.next": "Next",
  "article.englishOnly": "This article is available in English, French and Spanish for now. You are reading the English version.",
  "article.videoNotice": "This video is in English — French and Spanish versions are coming.",
  "article.video": "Watch the video",
  "article.onlyBadge": "Only in FieldQuo",
  "article.faq": "Frequently asked questions",
  "article.readIn": "Read this article in",
  "article.figureLangFallback": "Screen shown in English.",
  "footer.website": "FieldQuo website",
  "footer.pricing": "Pricing",
  "footer.privacy": "Privacy",
  "footer.terms": "Terms",
  "footer.rights": "All rights reserved.",
  "category.getting-started": "Getting started",
  "category.leads-and-quotes": "Leads & quotes",
  "category.jobs-and-scheduling": "Jobs & scheduling",
  "category.invoices-and-payments": "Invoices & getting paid",
  "category.clients": "Clients",
  "category.team-and-access": "Team & access",
  "category.marketing-and-website": "Marketing & website",
  "category.messages": "Messages",
  "category.mobile-and-crew": "On your phone & crew",
  "category.reports-and-insights": "Reports & insights",
  "category.settings": "Settings",
  "category.billing-and-subscription": "Billing & your subscription",
  "category.what-your-clients-see": "What your clients see",
  "category.integrations": "Integrations",
  "category.only-in-fieldquo": "Only in FieldQuo",
  "category.videos": "Videos",
  "blurb.getting-started": "Your first day, the sidebar, roles, imports and where to get help.",
  "blurb.leads-and-quotes": "From an enquiry to an approved price — quotes, add-ons, AI review, instant estimates.",
  "blurb.jobs-and-scheduling": "Jobs, visits, the calendar, crew shifts, time and tasks.",
  "blurb.invoices-and-payments": "Invoices, Stripe, fees and payouts, deposits, service plans.",
  "blurb.clients": "Client records, equipment, reviews and referrals.",
  "blurb.team-and-access": "Who sees what, seats, payroll, subcontractors, vehicles and purchasing.",
  "blurb.marketing-and-website": "Your website, funnels, campaigns, the designer and social posting.",
  "blurb.messages": "Facebook, Instagram and WhatsApp, the AI employee, texts, email and the receptionist.",
  "blurb.mobile-and-crew": "What the crew does on a phone: clock, photos, chat, schedule.",
  "blurb.reports-and-insights": "The dashboard, KPIs, how you compare, statements and expenses.",
  "blurb.settings": "Every row of the Settings menu, what it does and what it changes.",
  "blurb.billing-and-subscription": "Plans, seats, invoices from FieldQuo, changes and cancelling.",
  "blurb.what-your-clients-see": "The pages and emails a homeowner receives — with your name on them.",
  "blurb.integrations": "Stripe, Meta, WhatsApp, phones, maps, photos, email and your bookkeeper.",
  "blurb.only-in-fieldquo": "The things you will not find in the other products.",
  "blurb.videos": "Every article with a video, in one place.",
};

const fr = {
  "title": "Centre d'aide",
  "tagline": "Des guides pas à pas pour tout ce que fait FieldQuo — soumissions, chantiers, factures, encaissements, votre équipe, votre site web et l'utilisation sur téléphone.",
  "search.placeholder": "Chercher dans le centre d'aide…",
  "search.label": "Rechercher",
  "search.none": "Aucun article ne correspond à « {q} ».",
  "search.count": "{n} résultats pour « {q} »",
  "home.browse": "Parcourir par sujet",
  "home.popular": "Articles les plus consultés",
  "home.videos": "Vidéos",
  "home.count": "{n} articles",
  "nav.home": "Centre d'aide",
  "nav.signIn": "Se connecter",
  "nav.openApp": "Ouvrir FieldQuo",
  "nav.contact": "Joindre le soutien",
  "nav.language": "Langue",
  "nav.theme": "Changer de thème",
  "nav.menu": "Menu",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "Aide",
  "article.onThisPage": "Dans cet article",
  "article.updated": "Mis à jour le {date}",
  "article.related": "Articles liés",
  "article.helpful": "Cet article vous a-t-il aidé?",
  "article.yes": "Oui",
  "article.no": "Non",
  "article.thanks": "Merci — c'est noté.",
  "article.feedbackFailed": "Impossible d'envoyer pour l'instant.",
  "article.prev": "Précédent",
  "article.next": "Suivant",
  "article.englishOnly": "Cet article existe en anglais, en français et en espagnol pour l'instant. Vous lisez la version anglaise.",
  "article.videoNotice": "Cette vidéo est en anglais — les versions française et espagnole s'en viennent.",
  "article.video": "Voir la vidéo",
  "article.onlyBadge": "Seulement dans FieldQuo",
  "article.faq": "Questions fréquentes",
  "article.readIn": "Lire cet article en",
  "article.figureLangFallback": "Écran montré en anglais.",
  "footer.website": "Site FieldQuo",
  "footer.pricing": "Tarifs",
  "footer.privacy": "Confidentialité",
  "footer.terms": "Conditions",
  "footer.rights": "Tous droits réservés.",
  "category.getting-started": "Pour commencer",
  "category.leads-and-quotes": "Prospects et soumissions",
  "category.jobs-and-scheduling": "Chantiers et horaire",
  "category.invoices-and-payments": "Factures et encaissements",
  "category.clients": "Clients",
  "category.team-and-access": "Équipe et accès",
  "category.marketing-and-website": "Marketing et site web",
  "category.messages": "Messages",
  "category.mobile-and-crew": "Sur votre téléphone et l'équipe terrain",
  "category.reports-and-insights": "Rapports et indicateurs",
  "category.settings": "Réglages",
  "category.billing-and-subscription": "Facturation et votre abonnement",
  "category.what-your-clients-see": "Ce que vos clients voient",
  "category.integrations": "Intégrations",
  "category.only-in-fieldquo": "Seulement dans FieldQuo",
  "category.videos": "Vidéos",
  "blurb.getting-started": "Votre première journée, la barre latérale, les rôles, les imports et où trouver de l'aide.",
  "blurb.leads-and-quotes": "De la demande au prix approuvé — soumissions, options, révision par l'IA, estimations instantanées.",
  "blurb.jobs-and-scheduling": "Chantiers, visites, le calendrier, les quarts de l'équipe, le temps et les tâches.",
  "blurb.invoices-and-payments": "Factures, Stripe, frais et versements, acomptes, plans d'entretien.",
  "blurb.clients": "Fiches clients, équipements, avis et références.",
  "blurb.team-and-access": "Qui voit quoi, les sièges, la paie, les sous-traitants, les véhicules et les achats.",
  "blurb.marketing-and-website": "Votre site web, les entonnoirs, les campagnes, le designer et les publications.",
  "blurb.messages": "Facebook, Instagram et WhatsApp, l'employé IA, les textos, les courriels et la réceptionniste.",
  "blurb.mobile-and-crew": "Ce que l'équipe fait sur un téléphone : pointage, photos, clavardage, horaire.",
  "blurb.reports-and-insights": "Le tableau de bord, les indicateurs, votre position, les états et les dépenses.",
  "blurb.settings": "Chaque ligne du menu Réglages, ce qu'elle fait et ce qu'elle change.",
  "blurb.billing-and-subscription": "Forfaits, sièges, factures de FieldQuo, changements et annulation.",
  "blurb.what-your-clients-see": "Les pages et les courriels qu'un propriétaire reçoit — à votre nom.",
  "blurb.integrations": "Stripe, Meta, WhatsApp, téléphones, cartes, photos, courriel et votre comptable.",
  "blurb.only-in-fieldquo": "Ce que vous ne trouverez pas dans les autres logiciels.",
  "blurb.videos": "Tous les articles avec une vidéo, au même endroit.",
};

const es = {
  "title": "Centro de ayuda",
  "tagline": "Guías paso a paso para todo lo que hace FieldQuo: presupuestos, trabajos, facturas, cobros, su equipo, su sitio web y el uso desde el teléfono.",
  "search.placeholder": "Buscar en el centro de ayuda…",
  "search.label": "Buscar",
  "search.none": "Ningún artículo coincide con “{q}”.",
  "search.count": "{n} resultados para “{q}”",
  "home.browse": "Explorar por tema",
  "home.popular": "Artículos más leídos",
  "home.videos": "Videos",
  "home.count": "{n} artículos",
  "nav.home": "Centro de ayuda",
  "nav.signIn": "Iniciar sesión",
  "nav.openApp": "Abrir FieldQuo",
  "nav.contact": "Contactar con soporte",
  "nav.language": "Idioma",
  "nav.theme": "Cambiar tema",
  "nav.menu": "Menú",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "Ayuda",
  "article.onThisPage": "En este artículo",
  "article.updated": "Actualizado el {date}",
  "article.related": "Artículos relacionados",
  "article.helpful": "¿Le resultó útil?",
  "article.yes": "Sí",
  "article.no": "No",
  "article.thanks": "Gracias — anotado.",
  "article.feedbackFailed": "No se pudo enviar en este momento.",
  "article.prev": "Anterior",
  "article.next": "Siguiente",
  "article.englishOnly": "Este artículo está disponible en inglés, francés y español por ahora. Está leyendo la versión en inglés.",
  "article.videoNotice": "Este video está en inglés; las versiones en francés y español están en camino.",
  "article.video": "Ver el video",
  "article.onlyBadge": "Solo en FieldQuo",
  "article.faq": "Preguntas frecuentes",
  "article.readIn": "Leer este artículo en",
  "article.figureLangFallback": "Pantalla mostrada en inglés.",
  "footer.website": "Sitio de FieldQuo",
  "footer.pricing": "Precios",
  "footer.privacy": "Privacidad",
  "footer.terms": "Condiciones",
  "footer.rights": "Todos los derechos reservados.",
  "category.getting-started": "Primeros pasos",
  "category.leads-and-quotes": "Clientes potenciales y presupuestos",
  "category.jobs-and-scheduling": "Trabajos y programación",
  "category.invoices-and-payments": "Facturas y cobros",
  "category.clients": "Clientes",
  "category.team-and-access": "Equipo y accesos",
  "category.marketing-and-website": "Marketing y sitio web",
  "category.messages": "Mensajes",
  "category.mobile-and-crew": "En el teléfono y la cuadrilla",
  "category.reports-and-insights": "Informes e indicadores",
  "category.settings": "Configuración",
  "category.billing-and-subscription": "Facturación y su suscripción",
  "category.what-your-clients-see": "Lo que ven sus clientes",
  "category.integrations": "Integraciones",
  "category.only-in-fieldquo": "Solo en FieldQuo",
  "category.videos": "Videos",
  "blurb.getting-started": "Su primer día, la barra lateral, los roles, las importaciones y dónde pedir ayuda.",
  "blurb.leads-and-quotes": "De la consulta al precio aprobado: presupuestos, extras, revisión por IA, estimaciones instantáneas.",
  "blurb.jobs-and-scheduling": "Trabajos, visitas, el calendario, los turnos de la cuadrilla, el tiempo y las tareas.",
  "blurb.invoices-and-payments": "Facturas, Stripe, comisiones y transferencias, anticipos, planes de servicio.",
  "blurb.clients": "Fichas de clientes, equipos instalados, reseñas y referidos.",
  "blurb.team-and-access": "Quién ve qué, asientos, nómina, subcontratistas, vehículos y compras.",
  "blurb.marketing-and-website": "Su sitio web, embudos, campañas, el diseñador y las publicaciones sociales.",
  "blurb.messages": "Facebook, Instagram y WhatsApp, el empleado IA, mensajes de texto, correo y la recepcionista.",
  "blurb.mobile-and-crew": "Lo que la cuadrilla hace desde el teléfono: fichar, fotos, chat, horario.",
  "blurb.reports-and-insights": "El panel, los KPI, cómo se compara, estados financieros y gastos.",
  "blurb.settings": "Cada fila del menú Configuración, qué hace y qué cambia.",
  "blurb.billing-and-subscription": "Planes, asientos, facturas de FieldQuo, cambios y cancelación.",
  "blurb.what-your-clients-see": "Las páginas y correos que recibe un propietario, con su nombre.",
  "blurb.integrations": "Stripe, Meta, WhatsApp, teléfonos, mapas, fotos, correo y su contador.",
  "blurb.only-in-fieldquo": "Lo que no encontrará en los otros programas.",
  "blurb.videos": "Todos los artículos con video, en un solo lugar.",
};

const uk = {
  "title": "Довідковий центр",
  "tagline": "Покрокові посібники до всього у FieldQuo — кошториси, роботи, рахунки, оплати, ваша команда, ваш сайт і робота з телефона.",
  "search.placeholder": "Пошук у довідковому центрі…",
  "search.label": "Пошук",
  "search.none": "Немає статей за запитом «{q}».",
  "search.count": "{n} результатів за запитом «{q}»",
  "home.browse": "Переглянути за темами",
  "home.popular": "Популярні статті",
  "home.videos": "Відео",
  "home.count": "{n} статей",
  "nav.home": "Довідковий центр",
  "nav.signIn": "Увійти",
  "nav.openApp": "Відкрити FieldQuo",
  "nav.contact": "Звернутися в підтримку",
  "nav.language": "Мова",
  "nav.theme": "Змінити тему",
  "nav.menu": "Меню",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "Довідка",
  "article.onThisPage": "У цій статті",
  "article.updated": "Оновлено {date}",
  "article.related": "Пов'язані статті",
  "article.helpful": "Чи була ця стаття корисною?",
  "article.yes": "Так",
  "article.no": "Ні",
  "article.thanks": "Дякуємо — врахуємо.",
  "article.feedbackFailed": "Не вдалося надіслати зараз.",
  "article.prev": "Попередня",
  "article.next": "Наступна",
  "article.englishOnly": "Поки що ця стаття доступна англійською, французькою та іспанською. Ви читаєте англійську версію.",
  "article.videoNotice": "Це відео англійською — французька та іспанська версії готуються.",
  "article.video": "Переглянути відео",
  "article.onlyBadge": "Лише у FieldQuo",
  "article.faq": "Часті запитання",
  "article.readIn": "Читати цю статтю",
  "article.figureLangFallback": "Екран показано англійською.",
  "footer.website": "Сайт FieldQuo",
  "footer.pricing": "Ціни",
  "footer.privacy": "Конфіденційність",
  "footer.terms": "Умови",
  "footer.rights": "Усі права захищено.",
  "category.getting-started": "Початок роботи",
  "category.leads-and-quotes": "Ліди та кошториси",
  "category.jobs-and-scheduling": "Роботи та розклад",
  "category.invoices-and-payments": "Рахунки та оплата",
  "category.clients": "Клієнти",
  "category.team-and-access": "Команда та доступ",
  "category.marketing-and-website": "Маркетинг і сайт",
  "category.messages": "Повідомлення",
  "category.mobile-and-crew": "На телефоні та бригада",
  "category.reports-and-insights": "Звіти та показники",
  "category.settings": "Налаштування",
  "category.billing-and-subscription": "Оплата та ваша підписка",
  "category.what-your-clients-see": "Що бачать ваші клієнти",
  "category.integrations": "Інтеграції",
  "category.only-in-fieldquo": "Лише у FieldQuo",
  "category.videos": "Відео",
  "blurb.getting-started": "Перший день, бічна панель, ролі, імпорт і де шукати допомогу.",
  "blurb.leads-and-quotes": "Від запиту до затвердженої ціни — кошториси, додаткові опції, перевірка ШІ, миттєві оцінки.",
  "blurb.jobs-and-scheduling": "Роботи, візити, календар, зміни бригади, час і завдання.",
  "blurb.invoices-and-payments": "Рахунки, Stripe, комісії та виплати, завдатки, сервісні плани.",
  "blurb.clients": "Картки клієнтів, обладнання, відгуки та рекомендації.",
  "blurb.team-and-access": "Хто що бачить, місця, зарплата, субпідрядники, транспорт і закупівлі.",
  "blurb.marketing-and-website": "Ваш сайт, воронки, кампанії, дизайнер і публікації в соцмережах.",
  "blurb.messages": "Facebook, Instagram і WhatsApp, ШІ-працівник, SMS, електронна пошта та секретар.",
  "blurb.mobile-and-crew": "Що бригада робить із телефона: облік часу, фото, чат, розклад.",
  "blurb.reports-and-insights": "Панель, KPI, порівняння, звіти та витрати.",
  "blurb.settings": "Кожен рядок меню Налаштування — що він робить і що змінює.",
  "blurb.billing-and-subscription": "Тарифи, місця, рахунки від FieldQuo, зміни та скасування.",
  "blurb.what-your-clients-see": "Сторінки та листи, які отримує власник житла — з вашим іменем.",
  "blurb.integrations": "Stripe, Meta, WhatsApp, телефонія, карти, фото, пошта та ваш бухгалтер.",
  "blurb.only-in-fieldquo": "Те, чого немає в інших продуктах.",
  "blurb.videos": "Усі статті з відео в одному місці.",
};

const pa = {
  "title": "ਮਦਦ ਕੇਂਦਰ",
  "tagline": "FieldQuo ਦੀ ਹਰ ਚੀਜ਼ ਲਈ ਕਦਮ-ਦਰ-ਕਦਮ ਗਾਈਡ — ਕੋਟ, ਜੌਬ, ਇਨਵੌਇਸ, ਭੁਗਤਾਨ, ਤੁਹਾਡੀ ਟੀਮ, ਤੁਹਾਡੀ ਵੈੱਬਸਾਈਟ ਅਤੇ ਫ਼ੋਨ 'ਤੇ ਵਰਤੋਂ।",
  "search.placeholder": "ਮਦਦ ਕੇਂਦਰ ਵਿੱਚ ਖੋਜੋ…",
  "search.label": "ਖੋਜ",
  "search.none": "“{q}” ਨਾਲ ਕੋਈ ਲੇਖ ਨਹੀਂ ਮਿਲਿਆ।",
  "search.count": "“{q}” ਲਈ {n} ਨਤੀਜੇ",
  "home.browse": "ਵਿਸ਼ੇ ਅਨੁਸਾਰ ਦੇਖੋ",
  "home.popular": "ਪ੍ਰਸਿੱਧ ਲੇਖ",
  "home.videos": "ਵੀਡੀਓ",
  "home.count": "{n} ਲੇਖ",
  "nav.home": "ਮਦਦ ਕੇਂਦਰ",
  "nav.signIn": "ਸਾਈਨ ਇਨ ਕਰੋ",
  "nav.openApp": "FieldQuo ਖੋਲ੍ਹੋ",
  "nav.contact": "ਸਹਾਇਤਾ ਨਾਲ ਸੰਪਰਕ ਕਰੋ",
  "nav.language": "ਭਾਸ਼ਾ",
  "nav.theme": "ਥੀਮ ਬਦਲੋ",
  "nav.menu": "ਮੀਨੂ",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "ਮਦਦ",
  "article.onThisPage": "ਇਸ ਲੇਖ ਵਿੱਚ",
  "article.updated": "{date} ਨੂੰ ਅੱਪਡੇਟ ਕੀਤਾ",
  "article.related": "ਸੰਬੰਧਿਤ ਲੇਖ",
  "article.helpful": "ਕੀ ਇਹ ਮਦਦਗਾਰ ਸੀ?",
  "article.yes": "ਹਾਂ",
  "article.no": "ਨਹੀਂ",
  "article.thanks": "ਧੰਨਵਾਦ — ਨੋਟ ਕਰ ਲਿਆ।",
  "article.feedbackFailed": "ਹੁਣੇ ਭੇਜਿਆ ਨਹੀਂ ਜਾ ਸਕਿਆ।",
  "article.prev": "ਪਿਛਲਾ",
  "article.next": "ਅਗਲਾ",
  "article.englishOnly": "ਇਹ ਲੇਖ ਫ਼ਿਲਹਾਲ ਅੰਗਰੇਜ਼ੀ, ਫ਼ਰਾਂਸੀਸੀ ਅਤੇ ਸਪੈਨਿਸ਼ ਵਿੱਚ ਉਪਲਬਧ ਹੈ। ਤੁਸੀਂ ਅੰਗਰੇਜ਼ੀ ਸੰਸਕਰਣ ਪੜ੍ਹ ਰਹੇ ਹੋ।",
  "article.videoNotice": "ਇਹ ਵੀਡੀਓ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਹੈ — ਫ਼ਰਾਂਸੀਸੀ ਅਤੇ ਸਪੈਨਿਸ਼ ਸੰਸਕਰਣ ਆ ਰਹੇ ਹਨ।",
  "article.video": "ਵੀਡੀਓ ਦੇਖੋ",
  "article.onlyBadge": "ਸਿਰਫ਼ FieldQuo ਵਿੱਚ",
  "article.faq": "ਅਕਸਰ ਪੁੱਛੇ ਜਾਂਦੇ ਸਵਾਲ",
  "article.readIn": "ਇਹ ਲੇਖ ਇਸ ਭਾਸ਼ਾ ਵਿੱਚ ਪੜ੍ਹੋ",
  "article.figureLangFallback": "ਸਕ੍ਰੀਨ ਅੰਗਰੇਜ਼ੀ ਵਿੱਚ ਦਿਖਾਈ ਗਈ ਹੈ।",
  "footer.website": "FieldQuo ਵੈੱਬਸਾਈਟ",
  "footer.pricing": "ਕੀਮਤਾਂ",
  "footer.privacy": "ਪਰਦੇਦਾਰੀ",
  "footer.terms": "ਸ਼ਰਤਾਂ",
  "footer.rights": "ਸਾਰੇ ਹੱਕ ਰਾਖਵੇਂ ਹਨ।",
  "category.getting-started": "ਸ਼ੁਰੂਆਤ",
  "category.leads-and-quotes": "ਲੀਡ ਅਤੇ ਕੋਟ",
  "category.jobs-and-scheduling": "ਜੌਬ ਅਤੇ ਸ਼ਡਿਊਲ",
  "category.invoices-and-payments": "ਇਨਵੌਇਸ ਅਤੇ ਭੁਗਤਾਨ",
  "category.clients": "ਗਾਹਕ",
  "category.team-and-access": "ਟੀਮ ਅਤੇ ਪਹੁੰਚ",
  "category.marketing-and-website": "ਮਾਰਕੀਟਿੰਗ ਅਤੇ ਵੈੱਬਸਾਈਟ",
  "category.messages": "ਸੁਨੇਹੇ",
  "category.mobile-and-crew": "ਫ਼ੋਨ 'ਤੇ ਅਤੇ ਕਰੂ",
  "category.reports-and-insights": "ਰਿਪੋਰਟਾਂ ਅਤੇ ਅੰਕੜੇ",
  "category.settings": "ਸੈਟਿੰਗਾਂ",
  "category.billing-and-subscription": "ਬਿਲਿੰਗ ਅਤੇ ਤੁਹਾਡੀ ਸਬਸਕ੍ਰਿਪਸ਼ਨ",
  "category.what-your-clients-see": "ਤੁਹਾਡੇ ਗਾਹਕ ਕੀ ਦੇਖਦੇ ਹਨ",
  "category.integrations": "ਇੰਟੀਗ੍ਰੇਸ਼ਨ",
  "category.only-in-fieldquo": "ਸਿਰਫ਼ FieldQuo ਵਿੱਚ",
  "category.videos": "ਵੀਡੀਓ",
  "blurb.getting-started": "ਪਹਿਲਾ ਦਿਨ, ਸਾਈਡਬਾਰ, ਰੋਲ, ਇੰਪੋਰਟ ਅਤੇ ਮਦਦ ਕਿੱਥੋਂ ਲੈਣੀ ਹੈ।",
  "blurb.leads-and-quotes": "ਪੁੱਛਗਿੱਛ ਤੋਂ ਮਨਜ਼ੂਰ ਕੀਮਤ ਤੱਕ — ਕੋਟ, ਐਡ-ਆਨ, AI ਸਮੀਖਿਆ, ਤੁਰੰਤ ਅੰਦਾਜ਼ੇ।",
  "blurb.jobs-and-scheduling": "ਜੌਬ, ਵਿਜ਼ਿਟ, ਕੈਲੰਡਰ, ਕਰੂ ਸ਼ਿਫਟਾਂ, ਸਮਾਂ ਅਤੇ ਕੰਮ।",
  "blurb.invoices-and-payments": "ਇਨਵੌਇਸ, Stripe, ਫ਼ੀਸਾਂ ਅਤੇ ਭੁਗਤਾਨ, ਡਿਪਾਜ਼ਿਟ, ਸਰਵਿਸ ਪਲਾਨ।",
  "blurb.clients": "ਗਾਹਕ ਰਿਕਾਰਡ, ਉਪਕਰਣ, ਸਮੀਖਿਆਵਾਂ ਅਤੇ ਰੈਫ਼ਰਲ।",
  "blurb.team-and-access": "ਕੌਣ ਕੀ ਦੇਖਦਾ ਹੈ, ਸੀਟਾਂ, ਤਨਖ਼ਾਹ, ਸਬ-ਕੰਟਰੈਕਟਰ, ਵਾਹਨ ਅਤੇ ਖ਼ਰੀਦ।",
  "blurb.marketing-and-website": "ਤੁਹਾਡੀ ਵੈੱਬਸਾਈਟ, ਫਨਲ, ਮੁਹਿੰਮਾਂ, ਡਿਜ਼ਾਈਨਰ ਅਤੇ ਸੋਸ਼ਲ ਪੋਸਟਿੰਗ।",
  "blurb.messages": "Facebook, Instagram ਅਤੇ WhatsApp, AI ਕਰਮਚਾਰੀ, ਟੈਕਸਟ, ਈਮੇਲ ਅਤੇ ਰਿਸੈਪਸ਼ਨਿਸਟ।",
  "blurb.mobile-and-crew": "ਕਰੂ ਫ਼ੋਨ 'ਤੇ ਕੀ ਕਰਦਾ ਹੈ: ਕਲਾਕ, ਫ਼ੋਟੋ, ਚੈਟ, ਸ਼ਡਿਊਲ।",
  "blurb.reports-and-insights": "ਡੈਸ਼ਬੋਰਡ, KPI, ਤੁਲਨਾ, ਸਟੇਟਮੈਂਟ ਅਤੇ ਖ਼ਰਚੇ।",
  "blurb.settings": "ਸੈਟਿੰਗ ਮੀਨੂ ਦੀ ਹਰ ਕਤਾਰ, ਇਹ ਕੀ ਕਰਦੀ ਹੈ ਅਤੇ ਕੀ ਬਦਲਦੀ ਹੈ।",
  "blurb.billing-and-subscription": "ਪਲਾਨ, ਸੀਟਾਂ, FieldQuo ਦੇ ਇਨਵੌਇਸ, ਬਦਲਾਅ ਅਤੇ ਰੱਦ ਕਰਨਾ।",
  "blurb.what-your-clients-see": "ਉਹ ਪੰਨੇ ਅਤੇ ਈਮੇਲ ਜੋ ਘਰ ਦੇ ਮਾਲਕ ਨੂੰ ਮਿਲਦੇ ਹਨ — ਤੁਹਾਡੇ ਨਾਮ ਨਾਲ।",
  "blurb.integrations": "Stripe, Meta, WhatsApp, ਫ਼ੋਨ, ਨਕਸ਼ੇ, ਫ਼ੋਟੋ, ਈਮੇਲ ਅਤੇ ਤੁਹਾਡਾ ਲੇਖਾਕਾਰ।",
  "blurb.only-in-fieldquo": "ਉਹ ਚੀਜ਼ਾਂ ਜੋ ਹੋਰ ਸੌਫ਼ਟਵੇਅਰਾਂ ਵਿੱਚ ਨਹੀਂ ਮਿਲਣਗੀਆਂ।",
  "blurb.videos": "ਵੀਡੀਓ ਵਾਲਾ ਹਰ ਲੇਖ, ਇੱਕੋ ਥਾਂ।",
};

const tl = {
  "title": "Help Centre",
  "tagline": "Mga sunud-sunod na gabay para sa lahat ng nasa FieldQuo — quotes, trabaho, invoice, pagbabayad, ang iyong team, ang iyong website, at paggamit sa telepono.",
  "search.placeholder": "Maghanap sa help centre…",
  "search.label": "Maghanap",
  "search.none": "Walang artikulong tumutugma sa “{q}”.",
  "search.count": "{n} resulta para sa “{q}”",
  "home.browse": "Mag-browse ayon sa paksa",
  "home.popular": "Mga sikat na artikulo",
  "home.videos": "Mga video",
  "home.count": "{n} artikulo",
  "nav.home": "Help centre",
  "nav.signIn": "Mag-sign in",
  "nav.openApp": "Buksan ang FieldQuo",
  "nav.contact": "Makipag-ugnayan sa support",
  "nav.language": "Wika",
  "nav.theme": "Palitan ang tema",
  "nav.menu": "Menu",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "Tulong",
  "article.onThisPage": "Sa artikulong ito",
  "article.updated": "Na-update noong {date}",
  "article.related": "Mga kaugnay na artikulo",
  "article.helpful": "Nakatulong ba ito?",
  "article.yes": "Oo",
  "article.no": "Hindi",
  "article.thanks": "Salamat — naitala na.",
  "article.feedbackFailed": "Hindi maipadala sa ngayon.",
  "article.prev": "Nakaraan",
  "article.next": "Susunod",
  "article.englishOnly": "Sa ngayon, available ang artikulong ito sa Ingles, Pranses at Espanyol. Binabasa mo ang bersyong Ingles.",
  "article.videoNotice": "Nasa Ingles ang video na ito — paparating na ang bersyong Pranses at Espanyol.",
  "article.video": "Panoorin ang video",
  "article.onlyBadge": "Sa FieldQuo lang",
  "article.faq": "Mga madalas itanong",
  "article.readIn": "Basahin ang artikulong ito sa",
  "article.figureLangFallback": "Ipinapakita ang screen sa Ingles.",
  "footer.website": "Website ng FieldQuo",
  "footer.pricing": "Presyo",
  "footer.privacy": "Privacy",
  "footer.terms": "Mga tuntunin",
  "footer.rights": "Nakalaan ang lahat ng karapatan.",
  "category.getting-started": "Pagsisimula",
  "category.leads-and-quotes": "Mga lead at quote",
  "category.jobs-and-scheduling": "Mga trabaho at iskedyul",
  "category.invoices-and-payments": "Mga invoice at pagbabayad",
  "category.clients": "Mga kliyente",
  "category.team-and-access": "Team at access",
  "category.marketing-and-website": "Marketing at website",
  "category.messages": "Mga mensahe",
  "category.mobile-and-crew": "Sa telepono at ang crew",
  "category.reports-and-insights": "Mga ulat at insight",
  "category.settings": "Mga setting",
  "category.billing-and-subscription": "Billing at ang iyong subscription",
  "category.what-your-clients-see": "Ang nakikita ng iyong mga kliyente",
  "category.integrations": "Mga integrasyon",
  "category.only-in-fieldquo": "Sa FieldQuo lang",
  "category.videos": "Mga video",
  "blurb.getting-started": "Ang unang araw mo, ang sidebar, mga role, pag-import at kung saan hihingi ng tulong.",
  "blurb.leads-and-quotes": "Mula sa tanong hanggang sa aprubadong presyo — quotes, add-on, AI review, instant estimate.",
  "blurb.jobs-and-scheduling": "Mga trabaho, pagbisita, ang kalendaryo, shift ng crew, oras at mga task.",
  "blurb.invoices-and-payments": "Mga invoice, Stripe, bayarin at payout, deposito, service plan.",
  "blurb.clients": "Mga record ng kliyente, kagamitan, review at referral.",
  "blurb.team-and-access": "Sino ang nakakakita ng ano, seats, payroll, subcontractor, sasakyan at pagbili.",
  "blurb.marketing-and-website": "Ang iyong website, funnel, kampanya, ang designer at social posting.",
  "blurb.messages": "Facebook, Instagram at WhatsApp, ang AI employee, text, email at ang receptionist.",
  "blurb.mobile-and-crew": "Ang ginagawa ng crew sa telepono: clock, larawan, chat, iskedyul.",
  "blurb.reports-and-insights": "Ang dashboard, KPI, paghahambing, statement at gastos.",
  "blurb.settings": "Bawat hilera ng Settings menu, ano ang ginagawa nito at ano ang binabago.",
  "blurb.billing-and-subscription": "Mga plano, seats, invoice mula sa FieldQuo, pagbabago at pagkansela.",
  "blurb.what-your-clients-see": "Ang mga pahina at email na natatanggap ng may-ari ng bahay — sa pangalan mo.",
  "blurb.integrations": "Stripe, Meta, WhatsApp, telepono, mapa, larawan, email at ang iyong bookkeeper.",
  "blurb.only-in-fieldquo": "Ang mga bagay na hindi mo mahahanap sa ibang produkto.",
  "blurb.videos": "Bawat artikulong may video, sa isang lugar.",
};

const de = {
  "title": "Hilfe-Center",
  "tagline": "Schritt-für-Schritt-Anleitungen für alles in FieldQuo — Angebote, Aufträge, Rechnungen, Zahlungen, Ihr Team, Ihre Website und die Nutzung am Telefon.",
  "search.placeholder": "Im Hilfe-Center suchen…",
  "search.label": "Suchen",
  "search.none": "Kein Artikel passt zu „{q}“.",
  "search.count": "{n} Ergebnisse für „{q}“",
  "home.browse": "Nach Thema stöbern",
  "home.popular": "Beliebte Artikel",
  "home.videos": "Videos",
  "home.count": "{n} Artikel",
  "nav.home": "Hilfe-Center",
  "nav.signIn": "Anmelden",
  "nav.openApp": "FieldQuo öffnen",
  "nav.contact": "Support kontaktieren",
  "nav.language": "Sprache",
  "nav.theme": "Design wechseln",
  "nav.menu": "Menü",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "Hilfe",
  "article.onThisPage": "In diesem Artikel",
  "article.updated": "Aktualisiert am {date}",
  "article.related": "Verwandte Artikel",
  "article.helpful": "War das hilfreich?",
  "article.yes": "Ja",
  "article.no": "Nein",
  "article.thanks": "Danke — notiert.",
  "article.feedbackFailed": "Konnte gerade nicht gesendet werden.",
  "article.prev": "Zurück",
  "article.next": "Weiter",
  "article.englishOnly": "Dieser Artikel ist vorerst auf Englisch, Französisch und Spanisch verfügbar. Sie lesen die englische Fassung.",
  "article.videoNotice": "Dieses Video ist auf Englisch — die französische und spanische Fassung folgen.",
  "article.video": "Video ansehen",
  "article.onlyBadge": "Nur in FieldQuo",
  "article.faq": "Häufige Fragen",
  "article.readIn": "Diesen Artikel lesen auf",
  "article.figureLangFallback": "Bildschirm auf Englisch gezeigt.",
  "footer.website": "FieldQuo-Website",
  "footer.pricing": "Preise",
  "footer.privacy": "Datenschutz",
  "footer.terms": "Bedingungen",
  "footer.rights": "Alle Rechte vorbehalten.",
  "category.getting-started": "Erste Schritte",
  "category.leads-and-quotes": "Leads & Angebote",
  "category.jobs-and-scheduling": "Aufträge & Planung",
  "category.invoices-and-payments": "Rechnungen & Zahlungen",
  "category.clients": "Kunden",
  "category.team-and-access": "Team & Zugriff",
  "category.marketing-and-website": "Marketing & Website",
  "category.messages": "Nachrichten",
  "category.mobile-and-crew": "Am Telefon & im Team draußen",
  "category.reports-and-insights": "Berichte & Kennzahlen",
  "category.settings": "Einstellungen",
  "category.billing-and-subscription": "Abrechnung & Ihr Abonnement",
  "category.what-your-clients-see": "Was Ihre Kunden sehen",
  "category.integrations": "Integrationen",
  "category.only-in-fieldquo": "Nur in FieldQuo",
  "category.videos": "Videos",
  "blurb.getting-started": "Ihr erster Tag, die Seitenleiste, Rollen, Importe und wo es Hilfe gibt.",
  "blurb.leads-and-quotes": "Von der Anfrage zum bestätigten Preis — Angebote, Zusatzoptionen, KI-Prüfung, Sofortschätzungen.",
  "blurb.jobs-and-scheduling": "Aufträge, Termine, der Kalender, Schichten, Zeit und Aufgaben.",
  "blurb.invoices-and-payments": "Rechnungen, Stripe, Gebühren und Auszahlungen, Anzahlungen, Servicepläne.",
  "blurb.clients": "Kundendaten, Geräte, Bewertungen und Empfehlungen.",
  "blurb.team-and-access": "Wer was sieht, Plätze, Lohn, Subunternehmer, Fahrzeuge und Einkauf.",
  "blurb.marketing-and-website": "Ihre Website, Funnels, Kampagnen, der Designer und Social-Posts.",
  "blurb.messages": "Facebook, Instagram und WhatsApp, der KI-Mitarbeiter, SMS, E-Mail und die Rezeption.",
  "blurb.mobile-and-crew": "Was das Team am Telefon tut: Stempeln, Fotos, Chat, Zeitplan.",
  "blurb.reports-and-insights": "Das Dashboard, KPIs, Ihr Vergleich, Abschlüsse und Ausgaben.",
  "blurb.settings": "Jede Zeile des Einstellungsmenüs, was sie tut und was sie ändert.",
  "blurb.billing-and-subscription": "Tarife, Plätze, Rechnungen von FieldQuo, Änderungen und Kündigung.",
  "blurb.what-your-clients-see": "Die Seiten und E-Mails, die ein Hausbesitzer erhält — mit Ihrem Namen darauf.",
  "blurb.integrations": "Stripe, Meta, WhatsApp, Telefone, Karten, Fotos, E-Mail und Ihr Buchhalter.",
  "blurb.only-in-fieldquo": "Was Sie in den anderen Produkten nicht finden.",
  "blurb.videos": "Jeder Artikel mit Video, an einem Ort.",
};

const zh = {
  "title": "帮助中心",
  "tagline": "FieldQuo 各项功能的分步指南 — 报价、工单、发票、收款、团队、网站，以及在手机上的使用。",
  "search.placeholder": "搜索帮助中心…",
  "search.label": "搜索",
  "search.none": "没有与“{q}”匹配的文章。",
  "search.count": "“{q}”的 {n} 条结果",
  "home.browse": "按主题浏览",
  "home.popular": "热门文章",
  "home.videos": "视频",
  "home.count": "{n} 篇文章",
  "nav.home": "帮助中心",
  "nav.signIn": "登录",
  "nav.openApp": "打开 FieldQuo",
  "nav.contact": "联系支持",
  "nav.language": "语言",
  "nav.theme": "切换主题",
  "nav.menu": "菜单",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "帮助",
  "article.onThisPage": "本文内容",
  "article.updated": "更新于 {date}",
  "article.related": "相关文章",
  "article.helpful": "这篇文章有帮助吗？",
  "article.yes": "有",
  "article.no": "没有",
  "article.thanks": "谢谢，已记录。",
  "article.feedbackFailed": "暂时无法发送。",
  "article.prev": "上一篇",
  "article.next": "下一篇",
  "article.englishOnly": "本文目前提供英语、法语和西班牙语版本。您正在阅读英语版本。",
  "article.videoNotice": "本视频为英语 — 法语和西班牙语版本即将推出。",
  "article.video": "观看视频",
  "article.onlyBadge": "FieldQuo 独有",
  "article.faq": "常见问题",
  "article.readIn": "以其他语言阅读本文",
  "article.figureLangFallback": "屏幕以英语显示。",
  "footer.website": "FieldQuo 网站",
  "footer.pricing": "价格",
  "footer.privacy": "隐私",
  "footer.terms": "条款",
  "footer.rights": "保留所有权利。",
  "category.getting-started": "入门",
  "category.leads-and-quotes": "线索与报价",
  "category.jobs-and-scheduling": "工单与排程",
  "category.invoices-and-payments": "发票与收款",
  "category.clients": "客户",
  "category.team-and-access": "团队与权限",
  "category.marketing-and-website": "营销与网站",
  "category.messages": "消息",
  "category.mobile-and-crew": "手机端与施工队",
  "category.reports-and-insights": "报表与洞察",
  "category.settings": "设置",
  "category.billing-and-subscription": "账单与订阅",
  "category.what-your-clients-see": "客户看到的内容",
  "category.integrations": "集成",
  "category.only-in-fieldquo": "FieldQuo 独有",
  "category.videos": "视频",
  "blurb.getting-started": "第一天、侧边栏、角色、导入，以及去哪里寻求帮助。",
  "blurb.leads-and-quotes": "从询价到批准的价格 — 报价、附加项、AI 审核、即时估价。",
  "blurb.jobs-and-scheduling": "工单、上门、日历、班次、工时和任务。",
  "blurb.invoices-and-payments": "发票、Stripe、手续费与打款、定金、服务计划。",
  "blurb.clients": "客户档案、设备、评价与转介。",
  "blurb.team-and-access": "谁能看到什么、席位、工资、分包商、车辆和采购。",
  "blurb.marketing-and-website": "您的网站、漏斗、营销活动、设计器和社交发布。",
  "blurb.messages": "Facebook、Instagram 和 WhatsApp、AI 员工、短信、邮件和接待员。",
  "blurb.mobile-and-crew": "施工队在手机上做的事：打卡、照片、聊天、排班。",
  "blurb.reports-and-insights": "仪表盘、KPI、行业对比、财务报表和支出。",
  "blurb.settings": "设置菜单的每一行：它做什么、改变什么。",
  "blurb.billing-and-subscription": "套餐、席位、FieldQuo 的发票、变更与取消。",
  "blurb.what-your-clients-see": "房主收到的页面和邮件 — 署的是您的名字。",
  "blurb.integrations": "Stripe、Meta、WhatsApp、电话、地图、照片、邮件和您的会计。",
  "blurb.only-in-fieldquo": "其他产品里找不到的功能。",
  "blurb.videos": "所有带视频的文章，集中在一处。",
};

const it = {
  "title": "Centro assistenza",
  "tagline": "Guide passo passo per tutto ciò che fa FieldQuo — preventivi, lavori, fatture, incassi, il tuo team, il tuo sito web e l'uso da telefono.",
  "search.placeholder": "Cerca nel centro assistenza…",
  "search.label": "Cerca",
  "search.none": "Nessun articolo corrisponde a “{q}”.",
  "search.count": "{n} risultati per “{q}”",
  "home.browse": "Sfoglia per argomento",
  "home.popular": "Articoli più letti",
  "home.videos": "Video",
  "home.count": "{n} articoli",
  "nav.home": "Centro assistenza",
  "nav.signIn": "Accedi",
  "nav.openApp": "Apri FieldQuo",
  "nav.contact": "Contatta l'assistenza",
  "nav.language": "Lingua",
  "nav.theme": "Cambia tema",
  "nav.menu": "Menu",
  "nav.website": "fieldquo.com",
  "breadcrumb.home": "Aiuto",
  "article.onThisPage": "In questo articolo",
  "article.updated": "Aggiornato il {date}",
  "article.related": "Articoli correlati",
  "article.helpful": "È stato utile?",
  "article.yes": "Sì",
  "article.no": "No",
  "article.thanks": "Grazie — preso nota.",
  "article.feedbackFailed": "Impossibile inviare al momento.",
  "article.prev": "Precedente",
  "article.next": "Successivo",
  "article.englishOnly": "Per ora questo articolo è disponibile in inglese, francese e spagnolo. Stai leggendo la versione inglese.",
  "article.videoNotice": "Questo video è in inglese — le versioni francese e spagnola sono in arrivo.",
  "article.video": "Guarda il video",
  "article.onlyBadge": "Solo in FieldQuo",
  "article.faq": "Domande frequenti",
  "article.readIn": "Leggi questo articolo in",
  "article.figureLangFallback": "Schermata mostrata in inglese.",
  "footer.website": "Sito FieldQuo",
  "footer.pricing": "Prezzi",
  "footer.privacy": "Privacy",
  "footer.terms": "Termini",
  "footer.rights": "Tutti i diritti riservati.",
  "category.getting-started": "Per iniziare",
  "category.leads-and-quotes": "Contatti e preventivi",
  "category.jobs-and-scheduling": "Lavori e pianificazione",
  "category.invoices-and-payments": "Fatture e incassi",
  "category.clients": "Clienti",
  "category.team-and-access": "Team e accessi",
  "category.marketing-and-website": "Marketing e sito web",
  "category.messages": "Messaggi",
  "category.mobile-and-crew": "Da telefono e squadra",
  "category.reports-and-insights": "Report e indicatori",
  "category.settings": "Impostazioni",
  "category.billing-and-subscription": "Fatturazione e abbonamento",
  "category.what-your-clients-see": "Cosa vedono i tuoi clienti",
  "category.integrations": "Integrazioni",
  "category.only-in-fieldquo": "Solo in FieldQuo",
  "category.videos": "Video",
  "blurb.getting-started": "Il primo giorno, la barra laterale, i ruoli, le importazioni e dove chiedere aiuto.",
  "blurb.leads-and-quotes": "Dalla richiesta al prezzo approvato — preventivi, extra, revisione IA, stime istantanee.",
  "blurb.jobs-and-scheduling": "Lavori, visite, il calendario, i turni della squadra, il tempo e le attività.",
  "blurb.invoices-and-payments": "Fatture, Stripe, commissioni e accrediti, acconti, piani di servizio.",
  "blurb.clients": "Schede cliente, attrezzature, recensioni e segnalazioni.",
  "blurb.team-and-access": "Chi vede cosa, posti, paghe, subappaltatori, veicoli e acquisti.",
  "blurb.marketing-and-website": "Il tuo sito, i funnel, le campagne, il designer e i post social.",
  "blurb.messages": "Facebook, Instagram e WhatsApp, il dipendente IA, SMS, email e la receptionist.",
  "blurb.mobile-and-crew": "Cosa fa la squadra da telefono: timbrature, foto, chat, turni.",
  "blurb.reports-and-insights": "La dashboard, i KPI, il confronto, i bilanci e le spese.",
  "blurb.settings": "Ogni riga del menu Impostazioni, cosa fa e cosa cambia.",
  "blurb.billing-and-subscription": "Piani, posti, fatture di FieldQuo, modifiche e disdetta.",
  "blurb.what-your-clients-see": "Le pagine e le email che riceve un proprietario — con il tuo nome sopra.",
  "blurb.integrations": "Stripe, Meta, WhatsApp, telefoni, mappe, foto, email e il tuo commercialista.",
  "blurb.only-in-fieldquo": "Le cose che negli altri prodotti non troverai.",
  "blurb.videos": "Ogni articolo con un video, in un unico posto.",
};

export const HELP_CHROME = Object.freeze({ en, fr, es, uk, pa, tl, de, zh, it });
export const HELP_CHROME_LANGS = Object.freeze(Object.keys(HELP_CHROME));
export const HELP_CHROME_KEYS = Object.freeze(Object.keys(en));

/** The chrome strings for a language, falling back to English per key. */
export function helpT(lang) {
  const dict = HELP_CHROME[lang] || en;
  return (key, vars = null) => {
    let s = typeof dict[key] === "string" ? dict[key] : en[key] ?? key;
    if (vars) for (const [k, v] of Object.entries(vars)) s = s.split(`{${k}}`).join(String(v));
    return s;
  };
}

/** Is this a language the help centre renders chrome for? */
export function isHelpChromeLang(lang) {
  return Object.prototype.hasOwnProperty.call(HELP_CHROME, lang);
}
