// lib/help/content.js
//
// Server-side access to the help centre's words: the article modules under
// content/help/<lang>/, the video map, and the shapes the pages render.
//
// ── The article shape ──────────────────────────────────────────────────────
//
//   ARTICLES["slug"] = {
//     title:    "…",                      // the h1 and the <title>
//     summary:  "…",                      // one sentence: description, cards, search
//     updated:  "2026-09-12",             // ISO date, printed "Updated 12 Sep 2026"
//     intro:    ["paragraph", …],         // lead paragraphs above the outline
//     sections: [{ id, heading, blocks }],// h2s — the "In this article" outline
//     faq:      [{ q, a }],               // optional; rendered as the last section
//   }
//
// Blocks, one kind per object:
//   { p }  { steps: [] }  { bullets: [] }  { note } { tip } { warning }
//   { figure: "live:app-quotes", caption }  { table: { head: [], rows: [[]] } }
//
// Inline, inside any string: **bold** and [[slug|link text]] to another
// article. Nothing else — no HTML, ever. The renderer builds elements, so
// a stray < in a translation is text, not a tag.
//
// ── Languages ──────────────────────────────────────────────────────────────
//
// Bodies exist in HELP_LANGS (en, fr, es). Any other language the chrome
// speaks (lib/help/chrome.js) renders the ENGLISH body with a notice, never a
// machine translation — see lib/i18n/translateContent.js's header for why
// this codebase does not machine-translate anything a reader relies on.
// `langUsed` on the result says which body was served, so the page and the
// check can both see the fallback rather than infer it.

import { LOADERS } from "@/content/help/index.js";
// Both generated by scripts/build-help-content.mjs from content/help/videos.json
// (the owner's file) and from the figure copy. JS rather than JSON imports
// because bare node — which runs the check — needs an import attribute for
// JSON that the bundler does not, and one syntax both accept is worth a
// generated file.
import { VIDEOS as videosJson } from "@/content/help/videos.generated.js";
import { FIGURE_SOURCES as figuresJson } from "@/content/help/figures.generated.js";
import {
  HELP_LANGS,
  HELP_TREE,
  HELP_ARTICLES,
  REAL_CATEGORY_KEYS,
  articleMeta,
  virtualArticles,
} from "./tree";

/** The language whose BODY is served for a requested language. */
export function bodyLang(lang) {
  return HELP_LANGS.includes(lang) ? lang : "en";
}

/**
 * Which capture language answered each figure of a body language —
 * { "live-app-quotes": "fr" | "en" … } — written by
 * scripts/build-help-content.mjs when it copies the PNGs into public/help.
 * A figure absent from the map is assumed to be in the body language.
 */
export function figureSources(bodyLanguage) {
  return (figuresJson && figuresJson[bodyLanguage]) || {};
}

/** Video map, minus the "_about" note. */
export function videoMap() {
  const out = {};
  for (const [slug, v] of Object.entries(videosJson || {})) {
    if (slug.startsWith("_") || !v || typeof v.url !== "string") continue;
    out[slug] = {
      url: v.url,
      title: typeof v.title === "string" ? v.title : "",
      lang: typeof v.lang === "string" ? v.lang : "en",
      durationSec: Number.isFinite(Number(v.durationSec)) ? Number(v.durationSec) : null,
    };
  }
  return out;
}

/** How a video URL is embedded. YouTube → iframe; anything else → <video>. */
export function videoEmbed(url) {
  const u = String(url || "");
  const yt =
    /youtu\.be\/([A-Za-z0-9_-]{6,})/.exec(u) ||
    /youtube\.com\/(?:watch\?(?:.*&)?v=|embed\/|shorts\/)([A-Za-z0-9_-]{6,})/.exec(u);
  if (yt) return { kind: "youtube", src: `https://www.youtube-nocookie.com/embed/${yt[1]}` };
  if (/\.(mp4|webm|mov)(\?|$)/i.test(u)) return { kind: "file", src: u };
  return null;
}

/** Every article of one category in one language (body language rules apply). */
export async function loadCategory(lang, category) {
  const l = bodyLang(lang);
  const loader = LOADERS[l]?.[category];
  if (!loader) return {};
  const mod = await loader();
  return mod.ARTICLES || {};
}

/**
 * The list a category page shows: tree order, with the content module's
 * title and summary. An article the module has not written yet is OMITTED —
 * a card leading to an empty page is the dead control AGENTS.md forbids.
 */
export async function categoryList(lang, category) {
  const cat = REAL_CATEGORY_KEYS.includes(category) ? category : null;
  const videos = videoMap();
  let metas;
  if (cat) metas = HELP_TREE[cat].map((a) => ({ ...a, category: cat }));
  else if (category === "only-in-fieldquo") metas = virtualArticles("only");
  else if (category === "videos") metas = virtualArticles("video", videos);
  else return null;

  const byCategory = new Map();
  const out = [];
  for (const meta of metas) {
    if (!byCategory.has(meta.category)) byCategory.set(meta.category, await loadCategory(lang, meta.category));
    const art = byCategory.get(meta.category)[meta.slug];
    if (!art) continue;
    out.push({
      slug: meta.slug,
      category: meta.category,
      title: art.title,
      summary: art.summary,
      only: Boolean(meta.only),
      video: videos[meta.slug] || null,
    });
  }
  return out;
}

/** One article, with its neighbours and related list resolved to titles. */
export async function loadArticle(lang, category, slug) {
  const meta = articleMeta(slug);
  if (!meta || meta.category !== category) return null;
  // The body language, then English when that language has not written this
  // slug yet — a French reader gets the English article under an honest
  // notice rather than a 404. check:help-centre still requires parity, so
  // this is a safety net for the day between an English article landing and
  // its translations, not a licence to skip them.
  let l = bodyLang(lang);
  let articles = await loadCategory(l, category);
  let article = articles[slug];
  if (!article && l !== "en") {
    l = "en";
    articles = await loadCategory("en", category);
    article = articles[slug];
  }
  if (!article) return null;

  const siblings = HELP_TREE[category];
  const i = siblings.findIndex((a) => a.slug === slug);
  const neighbour = async (m) => {
    if (!m) return null;
    const a = articles[m.slug];
    return a ? { slug: m.slug, category, title: a.title } : null;
  };
  const prev = await neighbour(siblings[i - 1]);
  const next = await neighbour(siblings[i + 1]);

  // Related: the tree's explicit list first, then the category neighbours
  // that are not already there, capped so the block stays a block.
  const relatedSlugs = [];
  for (const s of meta.related || []) if (s !== slug && !relatedSlugs.includes(s)) relatedSlugs.push(s);
  for (const s of siblings.map((a) => a.slug)) {
    if (relatedSlugs.length >= 5) break;
    if (s !== slug && !relatedSlugs.includes(s)) relatedSlugs.push(s);
  }
  const related = [];
  const cache = new Map([[category, articles]]);
  for (const s of relatedSlugs) {
    const m = articleMeta(s);
    if (!m) continue;
    if (!cache.has(m.category)) cache.set(m.category, await loadCategory(l, m.category));
    const a = cache.get(m.category)[s];
    if (a) related.push({ slug: s, category: m.category, title: a.title });
  }

  const videos = videoMap();
  return {
    meta,
    article,
    langUsed: l,
    fallback: l !== lang,
    prev,
    next,
    related,
    video: videos[slug] || null,
  };
}

/** Every (category, slug) pair that has an English body — the static params. */
export async function writtenArticles() {
  const out = [];
  for (const category of REAL_CATEGORY_KEYS) {
    const en = await loadCategory("en", category);
    for (const a of HELP_TREE[category]) if (en[a.slug]) out.push({ category, slug: a.slug });
  }
  return out;
}

/** Resolve a link target [[slug|text]] to its category, or null. */
export function linkTarget(slug) {
  const m = articleMeta(slug);
  return m ? { category: m.category, slug } : null;
}

export { HELP_ARTICLES };
