// lib/kitchen/PlanPdf.jsx
//
// .jsx, not .js. Next compiles either, but esbuild — which the check script
// uses — refuses to parse JSX out of a .js file, and a renderer that can't be
// exercised outside the app is one nobody exercises at all.
//
// The PDF half of the presentation drawing.
//
// The other half is app/components/kitchen/PlanSvg.js. Both are thin adapters
// over the SAME shape list from planShapes — which is the entire reason that
// module returns primitives instead of markup. A client approves a drawing on
// screen and signs a PDF; if those were generated by two different code paths
// they would drift, and the drift would be invisible until a crew built from
// the wrong one.
//
// ── Which shape types must be supported ────────────────────────────────────
//
// Every one the SVG adapter handles. A shape silently skipped here is a cabinet
// missing from the printed plan — the drawing still looks plausible, which is
// what makes it dangerous. scripts/check-kitchen-plan.mjs asserts both adapters
// cover the same set.
//
// ── What @react-pdf can't do ───────────────────────────────────────────────
//
// No filters, no strokeLinecap, and text rotation works differently. The shape
// list was designed around that: shadows are stacked translucent rects rather
// than a blur filter, precisely so this file can draw them.
import React from "react";
import { Svg, Rect, Line, Circle, Path, Polygon, Text as SvgText, G } from "@react-pdf/renderer";
import { planShapes, elevationShapes, scaleBarShapes, legendShapes, PLAN_COLORS } from "./planShapes";
// Every <SvgText> below names the font explicitly. Text inside an <Svg> takes
// fontFamily as a PROP and @react-pdf defaults that prop to "Helvetica"
// independently of the enclosing <Page> style — so the plan title, which is
// the translated `kitchenPlan` label, kept truncating "План кухні" to bytes
// long after the rest of the page had moved to Noto.
import { PDF_FONT } from "@/lib/documents/pdfFont";

/** Every shape type planShapes can emit. Kept in sync with PlanSvg's switch. */
export const SUPPORTED_SHAPES = ["rect", "line", "circle", "path", "polygon", "text"];

/**
 * One shape → one @react-pdf node.
 *
 * @react-pdf takes stroke/fill as props, not as a style object, and it does NOT
 * accept `fill="none"` on every primitive the way SVG does — an undefined fill
 * is the reliable way to say "don't fill".
 */
function shapeNode(s, key) {
  const stroke = s.stroke || undefined;
  const strokeWidth = s.width ?? undefined;
  const fill = s.fill && s.fill !== "none" ? s.fill : undefined;
  const dash = s.dash ? s.dash.join(",") : undefined;
  const opacity = s.opacity ?? undefined;

  switch (s.type) {
    case "rect":
      return (
        <Rect
          key={key}
          x={s.x}
          y={s.y}
          width={s.w}
          height={s.h}
          rx={s.rx}
          fill={fill}
          stroke={stroke}
          strokeWidth={strokeWidth}
          strokeDasharray={dash}
          opacity={opacity}
        />
      );
    case "line":
      return (
        <Line
          key={key}
          x1={s.x1}
          y1={s.y1}
          x2={s.x2}
          y2={s.y2}
          stroke={stroke}
          strokeWidth={strokeWidth}
          strokeDasharray={dash}
          opacity={opacity}
        />
      );
    case "circle":
      return (
        <Circle
          key={key}
          cx={s.cx}
          cy={s.cy}
          r={s.r}
          fill={fill}
          stroke={stroke}
          strokeWidth={strokeWidth}
          opacity={opacity}
        />
      );
    case "path":
      return (
        <Path
          key={key}
          d={s.d}
          fill={fill}
          stroke={stroke}
          strokeWidth={strokeWidth}
          strokeDasharray={dash}
          opacity={opacity}
        />
      );
    case "polygon":
      return (
        <Polygon
          key={key}
          points={s.points.map((p) => p.join(",")).join(" ")}
          fill={fill}
          stroke={stroke}
          strokeWidth={strokeWidth}
          opacity={opacity}
        />
      );
    case "text":
      return (
        <SvgText
          key={key}
          x={s.x}
          y={s.y}
          fill={s.fill}
          // @react-pdf wants a number, and silently renders nothing useful for
          // a CSS-ish string.
          fontFamily={PDF_FONT}
          fontSize={Number(s.size) || 8}
          textAnchor={s.anchor}
          // Rotation is applied via a transform on the element, same as SVG, but
          // @react-pdf needs the rotation origin spelled out.
          transform={s.rotate ? `rotate(${s.rotate}, ${s.x}, ${s.y})` : undefined}
        >
          {s.text}
        </SvgText>
      );
    default:
      // Silently skipping would print a plan with a cabinet missing and no sign
      // that anything went wrong. Logged so it surfaces in the function log
      // rather than in a client's hands.
      console.warn(`[PlanPdf] unhandled shape type "${s.type}" — not drawn`);
      return null;
  }
}

/**
 * The plan, as a PDF <Svg>.
 *
 * @param width  the width to draw at, in PDF points. Height follows from the
 *               room's own aspect ratio, so a galley kitchen stays a galley
 *               kitchen rather than being squashed to a fixed box.
 */
export function PlanPdf({ design, width = 480, title, subtitle }) {
  const { shapes, width: W, height: H, pad, legend = [] } = planShapes(design);

  const headTop = title ? 26 : 0;
  const vbW = W + pad * 2;
  // The foot band is always 26 here — the PDF always draws the scale bar — and
  // the legend sits under it inside that band, at the same offset PlanSvg uses.
  const vbH = H + pad * 2 + headTop + 26;
  const height = (vbH / vbW) * width;

  const scale = scaleBarShapes({ x: -pad + 4, y: H + pad - 6, unitPx: 1 });
  const key = legendShapes(legend, { x: -pad + 4, y: H + pad + 16 });

  return (
    <Svg
      width={width}
      height={height}
      viewBox={`${-pad} ${-pad - headTop} ${vbW} ${vbH}`}
    >
      <G>
        {title && (
          <SvgText
            x={-pad + 4}
            y={-pad - headTop + 14}
            fill={PLAN_COLORS.ink}
            fontFamily={PDF_FONT}
            fontSize={13}
            textAnchor="start"
          >
            {String(title).toUpperCase()}
          </SvgText>
        )}
        {subtitle && (
          <SvgText
            x={-pad + 4}
            y={-pad - headTop + 25}
            fill={PLAN_COLORS.inkMuted}
            fontFamily={PDF_FONT}
            fontSize={9}
            textAnchor="start"
          >
            {subtitle}
          </SvgText>
        )}
        {shapes.map((s, i) => shapeNode(s, i))}
        {scale.map((s, i) => shapeNode(s, `sc${i}`))}
        {key.map((s, i) => shapeNode(s, `lg${i}`))}
      </G>
    </Svg>
  );
}

/** One wall elevation, as a PDF <Svg>. */
export function ElevationPdf({ design, wallId, width = 150 }) {
  const { shapes, width: W, height: H, title } = elevationShapes(design, wallId);
  const pad = 10;
  const head = 16;
  const vbW = W + pad * 2;
  const vbH = H + pad * 2 + head;
  const height = (vbH / vbW) * width;

  return (
    <Svg width={width} height={height} viewBox={`${-pad} ${-pad - head} ${vbW} ${vbH}`}>
      <G>
        <SvgText
          x={-pad + 2}
          y={-pad - 4}
          fill={PLAN_COLORS.ink}
          fontFamily={PDF_FONT}
          fontSize={7}
          textAnchor="start"
        >
          {title.toUpperCase()}
        </SvgText>
        {shapes.map((s, i) => shapeNode(s, i))}
      </G>
    </Svg>
  );
}

export { shapeNode };
